### ISSUE TITLE
Date Field Showing in task dialog box 

### ISSUE THREAD

**Issue by NishantSinghal19** [CCExtractor/taskwarrior-flutter#10]
It is not in a user-friendly format and also maintains that it should be changed while maintaining for task server format

**Comment by bhav-khurana** [comment]
Hello sir!
I would like to work on this issue.
Can you please assign it to me?

**Comment by bhav-khurana** [comment]
I hope this is what was desired (I have made minor UI changes also)
![Screenshot_2022-09-30-21-29-27-48_95710ad301893fdccf6b861c51c8d13a.jpg](https://user-images.githubusercontent.com/96694482/193310677-abef8977-d27c-4972-830b-0eb41812a9d5.jpg)

**Comment by piyushkumar12111111** [comment]
Please assign me this issue

**Comment by NishantSinghal19** [comment]
@bhav-khurana is this showing no issues? And also checked it is not violating model structure

**Comment by bhav-khurana** [comment]
> @bhav-khurana is this showing no issues? And also checked it is not violating model structure
> 
 I think it should work fine because I have created a new string that would be displayed in the due field and the rest of the variables stay the same... I have also made a PR regarding the same..can you please review it?

**Comment by NishantSinghal19** [comment]
check the details section of task and send ss in this issue

**Comment by bhav-khurana** [comment]
> check the details section of task and send ss in this issue
>

You mean this section?



![Screenshot_2022-10-01-15-53-23-97_95710ad301893fdccf6b861c51c8d13a.jpg](https://user-images.githubusercontent.com/96694482/193404970-85fb8f83-d016-4349-8500-547d7c8432a1.jpg)

**Comment by NishantSinghal19** [comment]
yes

**Comment by bhav-khurana** [comment]
Sir, is the PR fine?

**Comment by NishantSinghal19** [comment]
Yes
