### ISSUE TITLE
[FEAT]: Validation to new tag creator text field

### ISSUE THREAD

**Issue by shashvat1965** [CCExtractor/taskwarrior-flutter#101]
https://user-images.githubusercontent.com/68941739/220769537-04e2debd-64fa-4b9c-94f6-f658a09ca0b0.mov

Tags which have space cant be added which is logged as an error but no prompt is given to the user to fix this.

**Comment by shashvat1965** [comment]
should be fixed with #102

**Comment by Gitesg** [comment]
is this issue  still open?

**Comment by shashvat1965** [comment]
No ive made the pull request with required fix

**Comment by Gitesg** [comment]
ok
