### ISSUE TITLE
[Bug] Refresh button not working properly

### ISSUE THREAD

**Issue by bhav-khurana** [CCExtractor/taskwarrior-flutter#103]
Ideally, after clicking the refresh button, it should synchronize and update the details of the task. But currently, the task's 'last modified' property is not being changed. It remains the same even after clicking the refresh button. It should change to indicate the task's last modified time.

**Comment by bhav-khurana** [comment]
Please assign me this issue @NishantSinghal19 sir

**Comment by cfsmp3** [comment]
Issues can't be assigned. Just work on it and send a PR.
