### ISSUE TITLE
[BUG] Tasks which are added in past give an error on scheduling notification.

### ISSUE THREAD

**Issue by shashvat1965** [CCExtractor/taskwarrior-flutter#108]
Tasks which are made less than 1 min in past are ok since they still get notification.

Method to Reproduce:
1) Add a new task
2) Give a time of past

Console:
`E/flutter ( 5748): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (scheduledDate): Must be a date in the future: Instance of 'TZDateTime'`
`E/flutter ( 5748): #0      validateDateIsInTheFuture (package:flutter_local_notifications/src/helpers.dart:16:5)`
`E/flutter ( 5748): #1      AndroidFlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:209:5)`
`E/flutter ( 5748): #2      FlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:378:12)`
`E/flutter ( 5748): #3      NotificationService.sendNotification (package:taskwarrior/services/notification_services.dart:46:38)`
`E/flutter ( 5748): #4      _AddTaskBottomSheetState.build.<anonymous closure> (package:taskwarrior/widgets/addTask.dart:124:61)`

**Comment by kunal-gg** [comment]
What about a task that is scheduled in the past by date, are you checking for that

**Comment by kunal-gg** [comment]
Moreover if you think about this carefully, sometimes you may have tasks that were due but you didn't end up finishing them, It doesn't mean that you don't need them on the list.

**Comment by shashvat1965** [comment]
Yes im checking for that. What im doing  is converting the chosen date and time and given date and time to milliseconds since epoch and then comparing.

**Comment by salehdemir** [comment]
would you please assign me ?

**Comment by cfsmp3** [comment]
Issues can only be assigned to org members.

You can go ahead and work on it.

**Comment by shashvat1965** [comment]
I have already made a PR which fixes the issue.
