### ISSUE TITLE
Pem file generator in taskserver

### ISSUE THREAD

**Issue by NishantSinghal19** [CCExtractor/taskwarrior-flutter#11]
add server and credentials from freeinc and then make file to add in taskserver

**Comment by kunal-iitj** [comment]
Could you please elaborate on what do you actually want. I would like to make some contributions regarding this.

**Comment by sainideepanshu199** [comment]
can u please explain about this issue. 
I would like to work on it if it's still an issue.

**Comment by Pavel401** [comment]
@NishantSinghal19 please assign me this issue

**Comment by Pavel401** [comment]
Right now we can use any task server config in the app.
Tested with Wingtask, Freesinc,inthe.am servers.
