### ISSUE TITLE
A default alias should be there for newly added profiles

### ISSUE THREAD

**Issue by bhav-khurana** [CCExtractor/taskwarrior-flutter#118]
A default alias like "New Profile" should automatically be given to profiles that are newly added which can be renamed by the user anytime he wants.

**Comment by ZapeeoSheikh** [comment]
I have added pull request on this issue. Now, you will not get any issue related to this concern.

**Comment by NishantSinghal19** [comment]
Hey , I think i need profile id rather than new profile name as it is needed in Taskserver

**Comment by NishantSinghal19** [comment]
@Pavel401 i think you have also fixed this with your taskserver functionality

**Comment by Pavel401** [comment]
fixed in https://github.com/CCExtractor/taskwarrior-flutter/pull/192
