### ISSUE TITLE
STYLE: no colour change hint text

### ISSUE THREAD

**Issue by chandansgowda** [CCExtractor/taskwarrior-flutter#123]
The hint text in the homepage, "Click on the bottom right button to start adding tasks" stays dark even if DarkMode is switched on. This is probably because it is wrapped inside a widget declared as const.

![darkMode](https://user-images.githubusercontent.com/41890434/222436831-6c5aaa90-02af-4759-902e-d176a746202f.png)

**Comment by manoj1749** [comment]
A issue is already opened rergarding this and also I made a pr regarding it

**Comment by salehdemir** [comment]
please assign me this issue
