### ISSUE TITLE
[UI] Redesign the UI for Add Task, Dialog gets popped instead of showing Error

### ISSUE THREAD

**Issue by DenserMeerkat** [CCExtractor/taskwarrior-flutter#135]
### Describe the Problem

- The UI for Add Task Dialog looks very inconsistent and needs redesign.
- if due date field is left Empty, on Form validation the Dialog is popped and **SnackBar** is shown, instead of showing Error without popping dialog.

### Current UI for AddTask Dialog

Current UI Design             |  Pops Dialog and Shows SnackBar instead of Error
:-------------------------:|:-------------------------:
![Screenshot of Current Add Task UI](https://user-images.githubusercontent.com/95911940/224354765-42dfcadd-5219-4d5c-a1cd-00d7ffa18f9b.png) |  ![Screenshot when snackbar is displayed if due date is Empty](https://user-images.githubusercontent.com/95911940/224357835-e4129b49-a0f7-4dfb-a3a3-eaed09c19f4e.png)

### Are you working on this ?
- Yes

**Comment by Pavel401** [comment]
fixed on the latest https://github.com/CCExtractor/taskwarrior-flutter/pull/190
Thanks,
