### ISSUE TITLE
Add a validator for Due

### ISSUE THREAD

**Issue by Axhaat** [CCExtractor/taskwarrior-flutter#142]
There is no validator rather it throws an exception on clicking on the add button if the *due* is empty.

**Comment by DenserMeerkat** [comment]
PR : #136  fixes this issue

**Comment by simplybest12** [comment]
i want to fix this issue can i contribute ?? please reply

**Comment by Pavel401** [comment]
Fixed this issue on this pr https://github.com/CCExtractor/taskwarrior-flutter/pull/190
