### ISSUE TITLE
style: Splash Screen color improvement

### ISSUE THREAD

**Issue by rishabh-gurbani** [CCExtractor/taskwarrior-flutter#143]
Splash Screen of the app has blue background, which doesn't match the dark theme. Can be improved by matching the dark theme.
<img width="200" alt="Screenshot 2023-04-03 at 9 53 18 PM" src="https://user-images.githubusercontent.com/27919652/229580217-ee50e1d2-acbc-41e0-bdb9-593f4b1d41ef.png" >

**Comment by NishantSinghal19** [comment]
Merged
