### ISSUE TITLE
fix : placeholder shown on first load of app

### ISSUE THREAD

**Issue by rishabh-gurbani** [CCExtractor/taskwarrior-flutter#145]
Placeholder shown until directory fetched on first load.
Video Attached

https://user-images.githubusercontent.com/27919652/229592212-c3b5877f-397e-4411-b766-10523eb6b9e7.mp4

**Comment by simplybest12** [comment]
i want to contribute to this issue..can u please explain me the issue

**Comment by Pavel401** [comment]
fixed on this PR  #191
