### ISSUE TITLE
App closes on clicking Back button in profile page

### ISSUE THREAD

**Issue by Shubham9455** [CCExtractor/taskwarrior-flutter#15]
When we are clicking back button then it closes app instead of taking us to homepage(or main page) It is small issue but looking very bad when every time we have to open app from start

**Comment by Shubham9455** [comment]
@NishantSinghal19 please assign me this issue

**Comment by NishantSinghal19** [comment]
Where this issue is happening

**Comment by Shubham9455** [comment]
> Where this issue is happening

When the user is on profile page and clicking the back button

**Comment by Nix-Naman** [comment]
@Shubham9455 Hey i guess i can solve this issue. I would request you to assign me this issue.

**Comment by NishantSinghal19** [comment]
@Shubham9455 i am assigning please try to complete as soon as possible if not I will assign it to other person
