### ISSUE TITLE
Please delete illicit commits

### ISSUE THREAD

**Issue by bradyt** [CCExtractor/taskwarrior-flutter#153]
@Izaron
@canihavesomecoffee
@rkuchumov
@jesec
@saurabhshri
@satyammittal
@alexbrt
@aadibajpai
@PunitLodha
@Techno-Disaster
@Akshatji800
@NishantSinghal19

Your organization continues to harbor this repo and its illicit commits.

Are all of you aware of what happened, and continuing to support this organization?

@Techno-Disaster, can you clarify why you copied an advertisement vaguely claiming that my project did not exist, and then you did not fix it after learning the advertisement was false?

To apparently claim my project did not exist, then to solicit me for free work in private, requesting in private that I restructure my project for benefit of GSoC event, and then finally to take my work and remove authorship, and apply arbitrary license, I don't know why all members of CCExtractor would be okay with this. But that is my impression at this time.

In fact, I unfortunately feel that a large number of people even outside of this project, would prefer that my authorship be removed from what I wrote.

Please delete the commits, and ensure that all forks containing these commits, are addressed.

I don't know why an entire group of people would be against my authorship.

I would be curious if Carlos would state for the record that they had no idea my project existed before January 5th, 2022, when Carlos and Jayesh posted the misleading advertisement. But either way, the events that followed that, I find inappropriate. I would also be curious if Carlos, Nishant, Jayesh, and any other mentors and students involved, would state for the record that no mentors were aware that Nishant was taking code from my project. I'm also curious if Carlos or anyone else in CC Extractor was suggesting to apply an arbitrary license.

Please, finally, delete the commits, and address forks containing those commits.

**Comment by cfsmp3** [comment]
We don't care whether your project exists or not. 

When I started looking into doing this I didn't know that any project existed, then someone pointed me to your project, I reached out to you in case you want to collaborate and you refused, which is of course totally fine. 

So we decided to do our own thing.

Then you decided to email Google ??

I don't know what your problem is. This is open source. If someone took part of your code, did any derivative work, etc - go read your own license.

You seem to be really bored. 

Leave us alone. You continue with your project, do a better job that the people here that are just having fun coding during the summer and this project will fail. Assuming a for fun project can fail.

Feel free to take any code or license you like, as per the license.

**Comment by bradyt** [comment]
I was hoping someone else from the organization would step in, as you seemed to establish your interpretation of things in the previous thread. I'm not sure what your logic is with authorship and licenses. I can't reconcile what you're saying with what was discussed in the previous thread.

But as long as you're open to clarifying some other things. Can you please comment on those other aspects I asked about? Did you or other mentors know that Nishant or other students, were taking code from my project? Did you encourage them to remove trace of my authorship? Did you encourage them to apply MIT license? Did you encourage Nishant to claim the code was their own, and accept a stipend from Google?

I appreciate your apparent belief that all of this was fine. Then presumably you'll be forthright with each question.

I don't really understand your request to "leave us alone". I think some unfortunate steps were taken, and the damage is being perpetuated, and I'd like the organization to stop. Leave me alone.

This all seems pretty clear to me. I apologize to be accusative, but I don't think Carlos is being objective here or in other issues. Can someone else from the organization please step in, or does the entire organization agree with Carlos here?

**Comment by cfsmp3** [comment]
Please read GPL3 and GitHub terms of service and stop spamming.

If no one pays attention to what you are saying there's probably a reason.

You claim that people "took your code". You don't send a list of commits, or what the problem would be anyway since the license you freely chose explicitly allows it.

Now I hear you don't like forks.

Again, leave us alone. No one cares about your little project or our little project. We're building a Task Warrior client we like and that's all.

**Comment by canihavesomecoffee** [comment]
> I was hoping someone else from the organization would step in, as you seemed to establish your interpretation of things in the previous thread. I'm not sure what your logic is with authorship and licenses. I can't reconcile what you're saying with what was discussed in the previous thread.

Why would anyone else, which has not been involved at all with this project (or this fuss), step in? We're a very small org and have quite a number of totally different projects, so basically almost everyone (aside from Carlos, being the org founder and administrator) keeps only track of their own project(s).

> I don't really understand your request to "leave us alone". I think some unfortunate steps were taken, and the damage is being perpetuated, and I'd like the organization to stop. Leave me alone.

Time is scarce for most people, and you're taking up quite some of that (by CC'ing us in and forcing us to get to know what's actually going on), so I can *fully* understand Carlos' request to "leave us alone".

> This all seems pretty clear to me. I apologize to be accusative, but I don't think Carlos is being objective here or in other issues. Can someone else from the organization please step in, or does the entire organization agree with Carlos here?

As you can read above, it's a small org, where Carlos is the founder and only administrator. I see little use for anyone else to step in and handle these matters.

Besides, from my POV (from what I can see and understand the history), the only mistake that was made was not giving directly credit to you for certain portions of the code. That has been rectified as far as I'm aware now, so I don't see any existing problems anymore.

**Comment by bradyt** [comment]
> Besides, from my POV (from what I can see and understand the history), the only mistake that was made was not giving directly credit to you for certain portions of the code. That has been rectified as far as I'm aware now, so I don't see any existing problems anymore.

The commits remain as damage. Anyone can fork and use a previous commit, as is displayed at the fork Carlos mentions above.

> Now I hear you don't like forks.

**Comment by canihavesomecoffee** [comment]
That's a consequence of git. Why do you want to spend so much time and energy on all this? No one that wants to use the latest and greatest functionality of an app is going to use old, outdated code as a starting point. And if they use the latest code, you're credited.

**Comment by bradyt** [comment]
It's a consequence of actions. Git commits can be deleted. This organization is harboring illicit commits.

I'm afraid I don't understand how your last comment really addresses the issue. If you and I are at an impasse, does anyone else from the organization have input?

I feel like we're still at, illicit commits, looks approximately like plagiarism, and maybe fraud, if Nishant collected a stipend, and possible encouraged by mentors. And with the context of Carlos and Jayesh advertising that no such app exists. Very odd to go from, "no such app exists", to possibly, mentor instructing student to take that code, remove authorship, and add MIT license. Then when asked about it, Nishant tells me that they "took some reference". I ask for clarification, Nishant admits I'm author, then the comment is later deleted. Carlos steps in and starts insulting people vaguely.

When I asked Carlos to comment on these sort of potentialities above, he handwaved them, saying it's fine to take code and remove authorship.

I don't see a great reason for CC Extractor to keep these commits. Deleting the commits seems like a straightforward next step, given the amount of suspect behavior speculated at above.

I don't think this project was made in good faith. Let's all start to put this behind us.

**Comment by canihavesomecoffee** [comment]
> It's a consequence of actions. Git commits can be deleted. This organization is harboring illicit commits.

While we can _possibly_ "amend" this by rewriting the entire history (aka dropping the commits or altering them to immediately include the correct authorship, in as far as that was actually needed*), that won't change anything on the 54 forks this repository has by now. And that's certainly not a thing we (as an organisation) are gonna spend any of our scarce time on to reach out to those individual authors to update their forks.
 
> I'm afraid I don't understand how your last comment really addresses the issue. If you and I are at an impasse, does anyone else from the organization have input?

I'm afraid I don't understand why you keep hammering on having those commits removed, while the acknowledgement for certain parts of code were added in a later commit after you informed us about the similarities of certain pieces of code. 

Having commits removed require a forced rewrite of the history, which is, for actively forked projects a no-go:

> Do not rebase commits that exist outside your repository and that people may have based work on.
https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing

> And with the context of Carlos and Jayesh advertising that no such app exists. Very odd to go from, "no such app exists", to possibly, mentor instructing student to take that code, remove authorship, and add MIT license. 

If Carlos was not aware (which he said explicitly in the discussion above already), then reached out and you don't want to work together, fine. Your app was licensed at that time under GPLv3, so copying/gettting inspiration/... was allowed. The only fault that was happened here was that no attribution directly at the time he committed. I doubt this was done with any malicious intention.

> Carlos steps in and starts insulting people vaguely.

I see no insults anywhere, just Carlos not having any interest to spend time on this issue, and as such asking that single other person not to contribute any further to the discussion.

> When I asked Carlos to comment on these sort of potentialities above, he handwaved them, saying it's fine to take code and remove authorship.

Can you provide me with the exact quote where he said that? I find no references to any of those words.

> I don't see a great reason for CC Extractor to keep these commits. Deleting the commits seems like a straightforward next step, given the amount of suspect behavior speculated at above.

As stated above in my first answer, I don't see any reasons to go through all the hassle to remove them. We have given attribution in a later commit.

> I don't think this project was made in good faith. Let's all start to put this behind us.

I believe the opposite (I see no motives or actual indicators for bad faith at all), but I can concur with your last sentence. 

* As far as I've read in https://github.com/CCExtractor/taskwarrior-flutter/issues/58#issuecomment-1354151347, not all commits contain direct copied code.

**Comment by cfsmp3** [comment]
> It's a consequence of actions. Git commits can be deleted. This organization is harboring illicit commits.

Stop saying that, it's wrong (unless you can explain what an "illicit" commit is). Again, read GPLv3. And GitHub terms of service which are relevant now. You *explicitly* allow everyone to fork your code just by using GitHub.

And no, git commits can't be deleted. That's a very basic thing of distributed source control. You never rewrite history. 

> I'm afraid I don't understand how your last comment really addresses the issue. If you and I are at an impasse, does anyone else from the organization have input?

What do you think this organization is? It doesn't exist. It's just a group of developers hanging out and doing it because we enjoy it. It's not a formal entity that exists anywhere. 

> I feel like we're still at, illicit commits, looks approximately like plagiarism, and maybe fraud, if Nishant collected a stipend, and possible encouraged by mentors. And with the context of Carlos and Jayesh advertising that no such app exists. 

God, what advertising and why is it relevant if another app exists or not. 

Did we miss the part in where you were given exclusive rights to task warrior clients written in flutter?

>Very odd to go from, "no such app exists", to possibly, mentor instructing student to take that code, remove authorship,

I wonder what I'm doing engaging here... you are just making things up. Stop. We've been patient with your false accusations, childish emails to me personally and to Google, but you _are_ violating terms of service and we can also send emails.

> and add MIT license. Then when asked about it, Nishant tells me that they "took some reference". I ask for clarification, Nishant admits I'm author, then the comment is later deleted. Carlos steps in and starts insulting people vaguely.

Remind me who I insulted and how? 

> When I asked Carlos to comment on these sort of potentialities above, he handwaved them, saying it's fine to take code 

It absolutely is.

>and remove authorship.

I didn't say that.

> I don't see a great reason for CC Extractor to keep these commits. Deleting the commits seems like a straightforward next step, given the amount of suspect behavior speculated at above.

This is because you just ignore things such as licenses, terms of use, source control systems and so on.
> 
> I don't think this project was made in good faith. Let's all start to put this behind us.

Yes. Have a good life.

**Comment by bradyt** [comment]
@canihavesomecoffee this takes up a lot of time to review the above comments and questions, and write a thoughtful reply.

Your main issue seems to be why doesn't the commit saying portions of code were taken from a url fix things.

I wouldn't agree. The commits persist every day.
