### ISSUE TITLE
Task on the HomePage are in random Order

### ISSUE THREAD

**Issue by Shubham9455** [CCExtractor/taskwarrior-flutter#16]
Task shown on the HomePage are in random order, it may look great if they are sorted in decreasing order of urgency

**Comment by Shubham9455** [comment]
@NishantSinghal19 Please assign this issue to me

**Comment by NishantSinghal19** [comment]
I think the sorting feature will work and it can be random in order then it can change in user preference

**Comment by Shubham9455** [comment]
> I think the sorting feature will work and it can be random in order then it can change in user preference

Ya, I think that's fine.
