### ISSUE TITLE
How to test run this project?

### ISSUE THREAD

**Issue by n8henrie** [CCExtractor/taskwarrior-flutter#189]
I've tried to run this project on aarch64-darwin and x86_64-linux with no luck -- I get a browser window that opens with the TaskWarrior logo, but nothing else -- just the logo, no buttons ever appear, nothing ever happens.

I see this error in the output of `flutter run`, unsure if it is related:

```
Error: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/flutter/src/services/platform_channel.dart 308:7                     _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 156:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 840:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 869:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 641:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 715:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>
```

When I clone the project, `flutter pub get`, and then `flutter run`, what is supposed to happen?

**Comment by Pavel401** [comment]
@n8henrie  This project is available as a mobile application for both Android and iOS platforms. You have the option to build the APK locally or use the stable release build.

To perform a local build, you have the option to execute the project within an Android or iOS simulator. However, please note that Linux, Windows, and macOS platforms are currently not supported for local development.

**Comment by n8henrie** [comment]
Ah, okay. I saw the `web` directory and thought it would run on a desktop system in the web browser, but it sounds like that isn't the case.

Thanks for the help!
