### ISSUE TITLE
[Feature] A button to switch between Dark And Bright Mode

### ISSUE THREAD

**Issue by Shubham9455** [CCExtractor/taskwarrior-flutter#19]
# Bright Mode:
![Screenshot from 2022-10-03 13-12-01](https://user-images.githubusercontent.com/95691442/193530374-81e22519-666d-4327-92b3-d392cd598e30.png)

# Dark Mode:
![Screenshot from 2022-10-03 13-12-11](https://user-images.githubusercontent.com/95691442/193530416-46a91504-fe98-4254-bbcd-2b424a72a989.png)

**Comment by Shubham9455** [comment]
> # Bright Mode:
> ![Screenshot from 2022-10-03 13-12-01](https://user-images.githubusercontent.com/95691442/193530374-81e22519-666d-4327-92b3-d392cd598e30.png)
> 
> # Dark Mode:
> ![Screenshot from 2022-10-03 13-12-11](https://user-images.githubusercontent.com/95691442/193530416-46a91504-fe98-4254-bbcd-2b424a72a989.png)

@NishantSinghal19 Please Assign this issue to me

**Comment by NishantSinghal19** [comment]
Hey @Shubham9455 this is nice issue , But instead of making blue in dark mode I suggest you to reverse the color of app bar and main screen in dark mode , also you can give app bar greyish tone in dark mode. I am assigning you this issue

**Comment by Shubham9455** [comment]
> Hey @Shubham9455 this is nice issue , But instead of making blue in dark mode I suggest you to reverse the color of app bar and main screen in dark mode , also you can give app bar greyish tone in dark mode. I am assigning you this issue

Ok let me change it then

**Comment by ashishmohapatra240** [comment]
Hey, I want to work on this issue!

**Comment by Shubham9455** [comment]
![Screenshot from 2022-10-03 14-38-50](https://user-images.githubusercontent.com/95691442/193541132-1541ad5c-4df1-45e4-8d32-af8358bf260b.png)

Now Is it look fine, or I should change some other color patterns?

**Comment by adityar224** [comment]
@Shubham9455  That looks good.. Could I work on this?

**Comment by Shubham9455** [comment]
> @Shubham9455 That looks good.. Could I work on this?
@adityar224 
yes, i think u may find a lot of work in it as many pages need to be changes for dark mode

**Comment by adityar224** [comment]
@Shubham9455 
This issue just mentions a button to switch between the theme modes but not to actually implement the dark theme mode right?

**Comment by Shubham9455** [comment]
> @Shubham9455 This issue just mentions a button to switch between the theme modes but not to actually implement the dark theme mode right?

No It means we have to create a dark theme too

**Comment by NishantSinghal19** [comment]
I have merged your pull request @Shubham9455 this is looking nice

**Comment by NishantSinghal19** [comment]
Also can you made that default theme be according to your system

**Comment by NishantSinghal19** [comment]
@adityar224 you can work on it?

**Comment by adityar224** [comment]
Yess @NishantSinghal19
