### ISSUE TITLE
RenderFlex in the Profile page

### ISSUE THREAD

**Issue by MarkisDev** [CCExtractor/taskwarrior-flutter#2]
The profile page causes a render flex when the ExpansionTiles are expanded. See the pic attached for reference:
![qemu-system-x86_64_MMSNueUW4q](https://user-images.githubusercontent.com/28730791/192102734-7ccf4165-b0b0-46be-87b6-c00dff9f7e49.png)

This can have a very easy fix, I would like to work on it!

**Comment by NishantSinghal19** [comment]
Make the pull request and then i will review and merge it

**Comment by MarkisDev** [comment]
Done, please let me know if any changes is required!
