### ISSUE TITLE
fix: Add task screen color/theme doesnot follow dark theme mode

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#204]
## Description:
In the 'add task' screen, the window displays in colors similar to the light mode despite dark mode being active.

## Solution:
To address this, ensure a consistent theme or define a specific color theme for the widget. This can be done by choosing a color that complements the overall background of the app.

Please assign this issue to me.

## Problem Screenshots:
![4](https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/1ba88de3-b18a-416b-b962-072bb2369758)

**Comment by Pavel401** [comment]
Go ahead and implement. If you need any help let me know.
