### ISSUE TITLE
fix: "Add new Profile" Button unable to change colors as per app's theme (light/dark).

### ISSUE THREAD

**Issue by AayushPaigwar** [CCExtractor/taskwarrior-flutter#206]
# Description:
The button named "Add New Profile" in the profile section (home/menu/profile/) is unable to adapt the app's theme as expected, it retains the same appearance in both light and dark modes.

# Solution:
To fix this bug, make sure to check the app's theme first. Once that's clear, the elevated button will smartly pick the color according to the theme (Dark/Light).

Kindly assign this issue to me.

# Bug Screenshots:

| Screenshot- 1  (Dark Mode) |Screenshot- 2  (Light Mode) |
| --------------------------- | ---------------------------- |
| <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/8854aeda-d313-4718-9b21-71a258da4ea2" width="300" alt="Bug_DarkMode"> | <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/5f69e24e-0d75-4b9c-b492-5fdd45192c40" width="300" alt="Bug_LightMode">

**Comment by Pavel401** [comment]
No need to change.

**Comment by AayushPaigwar** [comment]
# Description (reason to fix): 
As I think in dark mode the user does not expect bright colors, so just to overcome that I have tried to fix the issue. 

# After fixing: 

| Screenshot- 1  (Dark Mode) |Screenshot- 2  (Light Mode) |
| --------------------------- | ---------------------------- |
| <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/4f1ca09d-ce91-4aa1-aa2a-e6ce32f9e1cd" width="300" alt="Bug_DarkMode"> | <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/b482f69e-d3e7-49dd-820c-ba0c32b10386" width="300" alt="Bug_LightMode">

# Before Fixing:

| Screenshot- 1  (Dark Mode) |Screenshot- 2  (Light Mode) |
| --------------------------- | ---------------------------- |
| <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/8854aeda-d313-4718-9b21-71a258da4ea2" width="300" alt="Bug_DarkMode"> | <img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/90213184/5f69e24e-0d75-4b9c-b492-5fdd45192c40" width="300" alt="Bug_LightMode">
