### ISSUE TITLE
style: Inconsistency in color theme on selecting due date for task

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#208]
# Description:
While working for #204 , I came across another UI bug:
The Calendar that shows up for selecting the due date is of the same light mode color scheme for both the dark mode as well as the light mode.
Please assign this issue to me.

# Screenshots:
![1](https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/dcdad609-835d-4e86-8079-511196836c92)
![2](https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/3818bdfb-c0fe-4a5f-91b4-c2293117dd67)

**Comment by Pavel401** [comment]
@its-me-abhishek are you still working on this issue?

**Comment by its-me-abhishek** [comment]
Yes, I am working on this issue. I have implemented the themes. Currently finding a solution for fixing the theme of textfield that appears in DatePicker.

**Comment by its-me-abhishek** [comment]
Please review my PR @Pavel401 , I have applied theme fixes to the datepicker as well as the timepicker widgets
