### ISSUE TITLE
Enhancement: closing previous snackbar while switiching profiles

### ISSUE THREAD

**Issue by RunTerror** [CCExtractor/taskwarrior-flutter#218]
https://github.com/CCExtractor/taskwarrior-flutter/assets/113206442/0eb774e3-9348-45ef-be86-17fb96e998d2

for better user experiece we can first close the previous snackbar and then showing the new snackbar.

**Comment by Photon3009** [comment]
https://github.com/CCExtractor/taskwarrior-flutter/assets/100941430/4ae7d307-c6e8-42d7-8d9b-36e1a24d91d9

@Pavel401 I have resolved the issue, please assign it to me
