### ISSUE TITLE
Enhancement: Color incosistency in drawer 

### ISSUE THREAD

**Issue by RunTerror** [CCExtractor/taskwarrior-flutter#219]
<img width="335" alt="Screenshot 2023-12-04 at 19 58 37" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/113206442/a37b3fca-be08-414e-869d-5e735a921acb">

we can make the whole drawer color while as it looks light purplish after drawer items.

**Comment by Pavel401** [comment]
No changes are needed for now.
