### ISSUE TITLE
[IMPROVEMENT] UI changes in the task list tile on the Home Page

### ISSUE THREAD

**Issue by bhav-khurana** [CCExtractor/taskwarrior-flutter#22]
The current list tile of task on the home page does not seem much user-readable and even hides some of the details as shown below

![WhatsApp Image 2022-10-03 at 20 28 31](https://user-images.githubusercontent.com/96694482/193610476-84342a06-9136-4d4a-821c-29071d723bd2.jpeg)

It would be better to expand the tile a bit and show the details in an organized way

**Comment by bhav-khurana** [comment]
@NishantSinghal19 sir can you please assign it to me?

**Comment by NishantSinghal19** [comment]
But i think the details will get more hidden by next version as details will mainly showed in task details page . It will only show urgency, id no. and probably time left b/w due date

**Comment by bhav-khurana** [comment]
How about this one ? @NishantSinghal19 
![WhatsApp Image 2022-10-03 at 20 19 59](https://user-images.githubusercontent.com/96694482/193789358-af19e5e3-b847-43cd-8446-1a902881c9a7.jpeg)

**Comment by NishantSinghal19** [comment]
No , it doesn't look good after opening the app details will be look simple on front page and project has sorting and that will come according to that. If you want to do details something make due date in some user friendly language

**Comment by bhav-khurana** [comment]
> No , it doesn't look good after opening the app details will be look simple on front page and project has sorting and that will come according to that. If you want to do details something make due date in some user friendly language
Okay sir, I will look into that
