### ISSUE TITLE
Bug: Validation error show before clicked "Add" button

### ISSUE THREAD

**Issue by prince02765** [CCExtractor/taskwarrior-flutter#226]
**How to Produce:**

1. Open App
2. Click on Floating Action Button (at the bottom right corner)
3. Now, you can see the validation check error in "Date" that is "Due date is required"

A validation error must be shown after clicking the add button. But, here is the opposite situation, so It's not good for user experience.

fix: A bug fix in the project

_Device Name: Samsung S21 5G
Android Version: 11_

<br>

**Screen Recording**

https://github.com/CCExtractor/taskwarrior-flutter/assets/69643676/047efbcd-08a8-4004-aaf7-57b45e5d6b06

**Comment by Photon3009** [comment]
hey @Pavel401, I have resolved this issue, if prince is not working on this, then I can raise a PR

**Comment by Photon3009** [comment]
@Pavel401 can you please assign this issue to me?
