### ISSUE TITLE
Issue in adding task, Showing past date

### ISSUE THREAD

**Issue by codesage01** [CCExtractor/taskwarrior-flutter#228]
User journey -
1.Start app and click on add button.
2.enter task then click on date in which.
3.Past date also shown.

Which represent that task also added for past but task we aiming to complete in future.  
fix: Issue fix by Hide previous date from your present calendar date.

This is attached video

https://github.com/CCExtractor/taskwarrior-flutter/assets/149355139/9b17c258-8c7b-4671-9210-d2726b3f7eb0

could you assign this issue to me?

**Comment by Photon3009** [comment]
hey @codesage01, this has already been fixed, maybe you have not synced your fork with the latest commits, please check it!
