### ISSUE TITLE
[IMPROVEMENT] Adding a drawer to reduce clutter in the App bar

### ISSUE THREAD

**Issue by stuck-in-a-conundrum** [CCExtractor/taskwarrior-flutter#23]
Putting a hamburger drawer on the corner of the appbar to reduce cluttered icons. 
Please assign this issue to me.

**Comment by NishantSinghal19** [comment]
Can you show some prototype or how would it look

**Comment by stuck-in-a-conundrum** [comment]
<img width="200" src="https://user-images.githubusercontent.com/85055775/193829348-2a6619c7-d8d5-4e9b-95ef-a74e32d9ee55.png">  <img src="https://user-images.githubusercontent.com/85055775/193829385-7b1a019f-5d1d-48bc-857b-12063e86619b.png" width="200">

This is how the hompage will look like after the changes.

**Comment by NishantSinghal19** [comment]
Can you make pr of this i would like to try the change then if it feels like user-friendly then I will merge it and I am also assigning you this issue
