### ISSUE TITLE
Feature: Adding Tutorial or Onboarding of app 

### ISSUE THREAD

**Issue by codesage01** [CCExtractor/taskwarrior-flutter#230]
Onboarding App Feature - Enhancing the User Journey

Adding a new onboarding feature to app can be a game-changer in terms of user engagement and retention. It sets the stage for a positive first impression, guiding users through the app's core functionalities and value propositions.

After Splash screen  we describe app function by focus mode.

feat: App tutorial through focus mode 

style: Feature and updates related to UI improvements and styling

Interactive App Tour: Navigate the app like a pro with  step-by-step guided tour. Highlight key features, demonstrate functionalities, and answer common questions along the way.

Personalized Recommendations: Based on  user interests and goals, we'll suggest relevant features and content to keep user engaged from the get-go. No more feeling lost in a sea of options!

Actionable Tips & Tricks: Go beyond the basics with bite-sized, actionable tips that unlock the app's hidden gems and power-up your experience.
Benefits:
   Enhanced User Satisfaction: A well-designed onboarding process reduces confusion and frustration, leading to happier users.

   Improved User Retention: By effectively showcasing the app's value, you encourage users to stick around and become loyal user.

   Personalized User Experience: Tailoring the onboarding to individual needs creates a more relevant and enjoyable experience.
   
   Can you assign this to me?

**Comment by codesage01** [comment]
@Pavel401 can i add showcaseview: ^2.0.3package by pubdev in dependencies it is required for app tutorial.

**Comment by Pavel401** [comment]
@codesage01 Sure

**Comment by its-me-abhishek** [comment]
can I work on this issue if it is stale?

**Comment by codesage01** [comment]
> can I work on this issue if it is stale?

Yes, but ask to @Pavel401  for assign
