### ISSUE TITLE
Date required when adding a new task

### ISSUE THREAD

**Issue by kiraslaugh** [CCExtractor/taskwarrior-flutter#231]
When I am trying to add a new task I am seeing text telling me that a due date is required to create a task. I thought it was kind of strange behavior because after you create the task it will allow you to delete the due date.

**Comment by cfsmp3** [comment]
@Pavel401 I'd say this is a bug... Creating tasks without a deadline (ie just "add to backlog") is quite common ans of course legal in task warrior.

Id say we should just make it optional.

**Comment by Pavel401** [comment]
> @Pavel401 I'd say this is a bug... Creating tasks without a deadline (ie just "add to backlog") is quite common ans of course legal in task warrior.
> 
> Id say we should just make it optional.

@cfsmp3 Sure, I will work on fixing that. Other users have also provided the same feedback.
