### ISSUE TITLE
Due date show incorrectly

### ISSUE THREAD

**Issue by kiraslaugh** [CCExtractor/taskwarrior-flutter#232]
I'm not sure if I am doing something wrong or not, but when I enter a due date it seems like the time is off by several hours from the time that I actually set.

**Comment by Pavel401** [comment]
@kiraslaugh Can you share more info about the issue?

**Comment by cfsmp3** [comment]
Just a guess but these things are usually timezone related.

**Comment by Pavel401** [comment]
https://github.com/CCExtractor/taskwarrior-flutter/pull/254 fixed
