### ISSUE TITLE
Add Context Filter

### ISSUE THREAD

**Issue by Rancho-rachit** [CCExtractor/taskwarrior-flutter#237]
## context filter

- Add a feature to sort tasks using a context filter
- [context docs](https://taskwarrior.org/docs/context/)

**Comment by nikkivirtuoso** [comment]
<img width="818" alt="Screenshot 2024-01-07 at 1 03 44 AM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/305e1695-da88-4fc1-9656-cf53fc6f9da4">
despite of defining the context it is coming can you help me ?

**Comment by nikkivirtuoso** [comment]
the website inthe.am is not responding and i am unable to test the app further please suggest me some alternatives so that i can start the syncserver and can contribute more to the taskwarrior

**Comment by Pavel401** [comment]
---

1. Sign up on [WingTask](https://app.wingtask.com/).
2. Navigate to the settings section.
3. Click on the "Download WingTask Configuration" button.
4. Extract the downloaded zip file.

Once extracted, you'll find the following files and folders:

- `install.sh`
- `README`
- `taskrc`
- `wingtask_certs`

![Files and Folders](https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/34fc908a-682d-426c-a5a9-54043a3c7583)

5. Copy the three files from the `wingtask_certs` folder and save them.

6. Open the `taskrc` file and copy the content of the following two lines:
   - `taskd.server`
   - `taskd.credentials`

![taskrc Content](https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/45b3c5b4-f459-4ebb-ba8f-582af8622d30)

7. Move the three copied files and the configuration from step 6 to your mobile device.

8. Paste the content of `taskd.server` and `taskd.credentials` into the respective fields under "Set taskrc" in the app.

![Paste Configurations](https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/77f71e5a-7325-4313-8fb1-18a7e6594810)

9. Configure the certificates in the app:
   - Select `example@gmail.com.cert.pem` for "Configure Server Certificate."
   - Select `example@gmail.com.key.pem` for "Configure TaskServer Key."
   - Select `letsencrypt_root_cert.pem` for "Configure Your Certificate."

![Configure Certificates](https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/8b73f087-152a-4207-9d93-87d0b87404d8)

10. Click on the "Stats" button in the app bar and check the response. If the response code is 200, you are good to go.

![Check Response](https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/21c82242-63fe-46d1-9f30-c681ca9a699f)

11. Sync your tasks and enjoy!

Feel free to reach out if you encounter any issues. 

@Rancho-rachit Can you add the wingtask tutorial in the readme file? Add screenshots and if possible a youtube video of the whole setup process.

**Comment by Pavel401** [comment]
> 1. Sign up on [WingTask](https://app.wingtask.com/).
> 2. Navigate to the settings section.
> 3. Click on the "Download WingTask Configuration" button.
> 4. Extract the downloaded zip file.
> 
> Once extracted, you'll find the following files and folders:
> 
> * `install.sh`
> * `README`
> * `taskrc`
> * `wingtask_certs`
> 
> ![Files and Folders](https://private-user-images.githubusercontent.com/47685150/294741987-34fc908a-682d-426c-a5a9-54043a3c7583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTE3NTAsIm5iZiI6MTcwNDYxMTQ1MCwicGF0aCI6Ii80NzY4NTE1MC8yOTQ3NDE5ODctMzRmYzkwOGEtNjgyZC00MjZjLWE1YTktNTQwNDNhM2M3NTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YWQ4OWJkODE4ZWQyZTM4M2U5MTEyODE0NTgyNWJjMjRmYjdmNTY2YmM0NWRhOGQwOTUwNThiMjNkZjFiODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5fxuR9yTHA89R5A0fHKLwSJKHhB8kGFYy_opig9nTM)
> 
> 5. Copy the three files from the `wingtask_certs` folder and save them.
> 6. Open the `taskrc` file and copy the content of the following two lines:
>    
>    * `taskd.server`
>    * `taskd.credentials`
> 
> ![taskrc Content](https://private-user-images.githubusercontent.com/47685150/294742191-45b3c5b4-f459-4ebb-ba8f-582af8622d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTE3NTAsIm5iZiI6MTcwNDYxMTQ1MCwicGF0aCI6Ii80NzY4NTE1MC8yOTQ3NDIxOTEtNDViM2M1YjQtZjQ1OS00ZWJiLWJhOGYtNTgyYWY4NjIyZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjVmOWM5YTlkNTFmNjkzY2FhYjU2OTM4ZDc1YjIxYzkzZTA4ZmFjZTA0ZTMxODlkYzg3MWY5ZDFhNTlkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzG2CS1xUUi646bkkxs6lD5QhMZTSgOY1fBL0kiUT1Y)
> 
> 7. Move the three copied files and the configuration from step 6 to your mobile device.
> 8. Paste the content of `taskd.server` and `taskd.credentials` into the respective fields under "Set taskrc" in the app.
> 
> ![Paste Configurations](https://private-user-images.githubusercontent.com/47685150/294742330-77f71e5a-7325-4313-8fb1-18a7e6594810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTE3NTAsIm5iZiI6MTcwNDYxMTQ1MCwicGF0aCI6Ii80NzY4NTE1MC8yOTQ3NDIzMzAtNzdmNzFlNWEtNzMyNS00MzEzLThmYjEtMThhN2U2NTk0ODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZjE0N2RiNjI1ZjkzNTExN2NmYzU0ZTllMTA0NjE1NGEyZmNiMWFjNGIxZTcyMTdmZjYwZjM1NTljNjVmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RGjJKtRngT5z-2MO4hxNeAd-YBkzjMKK8kTk3Lqa7eg)
> 
> 9. Configure the certificates in the app:
>    
>    * Select `example@gmail.com.cert.pem` for "Configure Server Certificate."
>    * Select `example@gmail.com.key.pem` for "Configure TaskServer Key."
>    * Select `letsencrypt_root_cert.pem` for "Configure Your Certificate."
> 
> ![Configure Certificates](https://private-user-images.githubusercontent.com/47685150/294742819-8b73f087-152a-4207-9d93-87d0b87404d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTE3NTAsIm5iZiI6MTcwNDYxMTQ1MCwicGF0aCI6Ii80NzY4NTE1MC8yOTQ3NDI4MTktOGI3M2YwODctMTUyYS00MjA3LTlkOTMtODdkMGI4NzQwNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzNjNTg5MWZhYWU2ODhiNDgyOTM2ZGJmNTBmYTA5ZGZlOTM1YmY4ODlmOWRiOWYyMDJiNmNiNGQ1ZmIwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bT_-BA9HyerBvBPp31zZZXFNYRQDKrcj0mCmmTTQvE)
> 
> 10. Click on the "Stats" button in the app bar and check the response. If the response code is 200, you are good to go.
> 
> ![Check Response](https://private-user-images.githubusercontent.com/47685150/294742696-21c82242-63fe-46d1-9f30-c681ca9a699f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTE3NTAsIm5iZiI6MTcwNDYxMTQ1MCwicGF0aCI6Ii80NzY4NTE1MC8yOTQ3NDI2OTYtMjFjODIyNDItNjNmZS00NmQxLTlmMzAtYzY4MWNhOWE2OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDhkZGFkMzZmOWQ1ZTk5MTIwMDhlZGQwMzA1ZDhhOWRkYWJlY2MwZDk2MzNiODBiN2I4Y2M2Yjk2OGM5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6YlH8KesDbfGM3SRlAbOF7cnKBaXCU8ZjnNLWi0R6Gc)
> 
> 11. Sync your tasks and enjoy!
> 
> Feel free to reach out if you encounter any issues.
> 
> @Rancho-rachit Can you add the wingtask tutorial in the readme file? Add screenshots and if possible a youtube video of the whole setup process.

@nikkivirtuoso check this
