### ISSUE TITLE
After clicking on the OK Button of due clock the screen freezes and an error occured

### ISSUE THREAD

**Issue by nikkivirtuoso** [CCExtractor/taskwarrior-flutter#240]
the Error is:
force finish cuj, time out: J<IME_INSETS_ANIMATION::1@1@com.ccextractor.taskwarriorflutter>

i have synced my app, i am running the app on android, here are the screenshots of the issue:
<img width="361" alt="Screenshot 2024-01-07 at 8 16 16 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/838655cd-9272-4411-a71c-686541fff916">
here is the screenshot of the error
<img width="1141" alt="Screenshot 2024-01-07 at 8 45 14 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/bf3c67b6-6c36-47ec-b40e-7e3c9aacfb0a">

I searched it and find that: This suggests that there was a forced termination of something (possibly a task or operation) due to a timeout. Where is the problem ? 
and the code in the statistics is 200 after configuring all the settings
<img width="351" alt="Screenshot 2024-01-07 at 8 47 55 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/d5b5a526-271e-4373-a47e-5a04919dcd7b">

**Comment by abhisheksharma010** [comment]
Hello , can you assign this issue to me? I can easily resolve this.

**Comment by abhisheksharma010** [comment]
Sorry sir @Pavel401 , for the delay. I missed the email. I sincerely apologize. Within one day, I am going to complete this. Today, I am checking my emails, and I found this. Really sorry.

**Comment by abhisheksharma010** [comment]
Hello, sir. There is no issue, according to me, because of multiple apps or any other mobile-related issue. That thing happened when the app is running smoothly. I have checked it, and I do not find any issue. I tried it multiple times. However, when I opened multiple apps in the background and performed this task, the app hung. There is no issue in the app.

**Comment by JangamRuthvik** [comment]
i think we can close this issue @Pavel401

**Comment by Pavel401** [comment]
Thanks for checking
