### ISSUE TITLE
Bug : Filter menu display problems

### ISSUE THREAD

**Issue by tfatts** [CCExtractor/taskwarrior-flutter#244]
Hi, thank you very much for this app, it's been very useful ! 

### Describe your issue
Sometimes, the "Apply Filters" menu fails to display correctly, and displays as a light gray empty 

### Steps to reproduce
I had it happen for other reasons (and couldn't find why) but it can be reliably triggered by following those steps : 
- Create a task and assign it to the project "project1"
- Create another task and assign it to the subproject "project1.subproject1"
- Open the Apply Filters and click on "project1" (not on the checkbox, the text "project1"). It will display the subproject "project1.subproject1".
- Close the "Apply Filters" menu by swiping right.
- Open the "Apply Filters" menu by swiping left. It will be gray.

### What was the expected result?
It should display the "Apply Filters" menu. Instead, it is gray.

### Put here any screenshots or videos (optional) : 
![Screenshot_20240122-093019_TaskWarrior](https://github.com/CCExtractor/taskwarrior-flutter/assets/115453194/3019fbd0-5936-43f0-8aca-2fbb7b6e0b2d)

### How can we contact you (optional)
No response

### Would you like to work on this issue?
No, I don't know anything about flutter :/

### By submitting this issue, I have confirmed that:
    I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

edit: I have edited the issue to fit the correct format

**Comment by tfatts** [comment]
On a tablet, after following the same steps, I had this : ![Screenshot_2024-01-23-15-32-10-567](https://github.com/CCExtractor/taskwarrior-flutter/assets/115453194/2cc9e696-554b-49e1-b571-8b5773306316)

**Comment by Kaps61929** [comment]
@Pavel401, I would love to contribute to this issue. Please assign it to me.
