### ISSUE TITLE
Incorrect Time Zone Conversion in Taskwarrior App

### ISSUE THREAD

**Issue by vkprogrammer-001** [CCExtractor/taskwarrior-flutter#248]
In the Taskwarrior app, when setting a specific time (e.g., 2:00 PM), the app displays a time corresponding to a different time zone (e.g., 8:30 AM). This behavior is inconsistent with the expected functionality, as the app should display the time as per the user’s local time zone. This issue could lead to potential confusion and mismanagement of tasks. A fix to ensure correct time zone conversion and display is needed.
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/143318563/a18c2fd5-fd64-48fd-8ea3-5457df4213eb" height = "600px" width = "300px" alt = "time"></br>
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/143318563/88a1e021-2bdd-4bee-ad2a-6f581f25fca1" height = "600px" width = "300px" alt = "dueTime">

**Comment by its-me-abhishek** [comment]
convert the timezone of localvalue to local in `task_details.dart` and it's fixed.

**Comment by abhisheksharma010** [comment]
Yes i know and there other ways also

**Comment by abhisheksharma010** [comment]
Yes and there are more ways to deal with this

**Comment by vkprogrammer-001** [comment]
@abhisheksharma010 yes I am working on this issue

**Comment by vkprogrammer-001** [comment]
thanks for the help @its-me-abhishek
