### ISSUE TITLE
Enhancing App Functionality with Tag Feature

### ISSUE THREAD

**Issue by abhisheksharma010** [CCExtractor/taskwarrior-flutter#251]
### Describe your improvement idea or feature request

Considering improvements for our app, I propose the addition of a tag feature during the creation process. This would include incorporating default tags such as 'school,' 'housework,' 'office,' etc. This enhancement aims to streamline organization and categorization. I'm excited about working on this modification to make our app even better.

### How would you like to see it implemented?

I envision the implementation of the tag feature to be user-friendly and intuitive. Users could have the option to easily add tags during the app creation process or while managing their tasks. The default tags like 'school,' 'housework,' 'office,' etc., would provide a helpful starting point for organization. Additionally, a simple interface for adding, editing, and removing tags would contribute to a seamless user experience. I look forward to collaborating on this implementation to ensure it aligns with our users' needs and preferences

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
@abhisheksharma010 one request: keep it as an optional parameter. If the user wants to choose a tag, then okay, otherwise create an empty task with the task name.
