### ISSUE TITLE
Unnecessary Alert on Unchanged Task Page Exit

### ISSUE THREAD

**Issue by Kaps61929** [CCExtractor/taskwarrior-flutter#260]
### Describe your issue

When no changes have been made on the task detail page, navigating back should occur directly instead of displaying an alert box prompting to save changes.

### Steps to reproduce

1)Navigate to the task detail page.
2)Without making any changes, attempt to navigate back to the previous page.
3)Instead of a direct navigation, observe if an alert box appears prompting to save changes, even though no modifications have been made.

### Put here any screenshots or videos (optional)

https://github.com/CCExtractor/taskwarrior-flutter/assets/115138974/cbf65146-6837-4ab3-950e-3cf0016d9287

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by yaviral17** [comment]
ok this is happening because there are no checks in saveChanges() function inside lib\services\task_details.dart  at line no: 48 , so when ever any user tries to go back by taping on yes in the dialog box it updates the last modified time .

a quick solution to it is by checking if callback() function is been called to assume that user has tried to modify values and according to that we can directly pop from saveChanges() if callback() function  is never called else do the same

**Comment by Kaps61929** [comment]
@yaviral17, yes, I also thought the same solution.

**Comment by yaviral17** [comment]
So I was thinking to work on it as I am new to open source and it's a good to go task for me

**Comment by Kaps61929** [comment]
@yaviral17 
I have already started working on it

**Comment by yaviral17** [comment]
okay sure but I have already fixed it so I am ready to make a PR

**Comment by Kaps61929** [comment]
@yaviral17, I have been assigned to work on this issue. Please be respectful to others if they are already assigned to a particular task. Additionally, directly setting a bool variable in 'canPop' may trigger 'Navigator.pop()' and could lead to issues related to the navigation stack and memory. I faced a similar problem in issue #256, so to address it, we used 'Navigator.of(context).pushAndRemoveUntil(
MaterialPageRoute(builder: (context) => const HomePage()),
(Route<dynamic> route) => false)' method, which I have included in my pull request.
