### ISSUE TITLE
[IMPROVEMENT] Home Page UI

### ISSUE THREAD

**Issue by 100RAV-AGGARWAL** [CCExtractor/taskwarrior-flutter#27]
Improved the Task List Item for better readability and the priority are clearly visible through colored icons.
![Taskwarrior home page](https://user-images.githubusercontent.com/81032655/194280932-717dcf2e-b548-4f29-ae8b-b98d1447971b.jpeg)

![Taskwarrior home page 2](https://user-images.githubusercontent.com/81032655/194281971-fea65cdc-5778-483a-be54-e656d14b1303.jpeg)

This is the app preview after the changes. I would like you to assign this improvement issue to me.

**Comment by NishantSinghal19** [comment]
It is looking nice, I am assigning this issue please make the pr and then i will review it
