### ISSUE TITLE
Improve alert box

### ISSUE THREAD

**Issue by abhisheksharma010** [CCExtractor/taskwarrior-flutter#277]
### Describe your improvement idea or feature request

The 'Cancel' button looks a bit odd. We can enhance its appearance by using an alert box package to create a more visually appealing and attractive alert box.

### How would you like to see it implemented?

![Screenshot_2024-02-04-15-09-44-94_60662d71d3a472201be58e3fd69f71f0](https://github.com/CCExtractor/taskwarrior-flutter/assets/108579257/1e2c8b5c-9405-458f-a44e-c7dc73ccee85)

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
Can we do the same without using any extra package ?

**Comment by abhisheksharma010** [comment]
I have successfully implemented this using packages in previous projects. Positioning the cross (x) icon in the top right corner can be challenging, requiring a trial-and-error approach. I will try to attempt the task without using a package and provide you with detailed results by yesterday.

**Comment by abhisheksharma010** [comment]
I have tried without using extra packages, but I do not get the proper UI

**Comment by Pavel401** [comment]
Please mention the package name and the expected result of the UI.

**Comment by abhisheksharma010** [comment]
Sir, I have tried  but i do not get ui that in mind. and the curret one is better and consistent with the app
