### ISSUE TITLE
Searching using voice

### ISSUE THREAD

**Issue by Kaps61929** [CCExtractor/taskwarrior-flutter#284]
### Describe your improvement idea or feature request

Introducing voice search functionality in Taskwarrior enhances user accessibility and convenience. Users can now effortlessly initiate searches by clicking on the speaker icon within the search bar. This feature allows for a hands-free approach, letting individuals simply speak their search queries instead of manually typing them. By integrating voice search, Taskwarrior aims to streamline the user experience, offering a quick and efficient alternative for users to interact with the application.

### How would you like to see it implemented?

1. **Voice Search Integration:**
   - Add a speaker icon to the search bar for voice search activation.

2. **User Interaction:**
   - Users can click on the speaker icon to initiate voice-based search.

3. **Clear and Execute:**
   - Implement speech recognition to process spoken words, execute the search, and offer an option to clear voice input for 
   user flexibility.

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
I don't think this feature is necessary as of now. The app already has filters and a search feature.
