### ISSUE TITLE
Option to user in Timepicker to change Time Formate 24hour or 12 hour

### ISSUE THREAD

**Issue by codesage01** [CCExtractor/taskwarrior-flutter#286]
### Describe your improvement idea or feature request

Flexibility: Users can choose the format that's most familiar and comfortable for them, leading to a better user experience.

Clarity: Especially in tasks involving precise time tracking or international collaboration, displaying time in the preferred format ensures clarity and reduces confusion.

Improved data accuracy: Users are less likely to make mistakes while entering or reading time if it's displayed in their preferred format.

### How would you like to see it implemented?

1.Go to add icon
2.Select  24 hour format(to change from 12 hour to 24) or 12 hour format is automatically enabled

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
@codesage01 any update ?
