### ISSUE TITLE
Error in LandScape mode

### ISSUE THREAD

**Issue by JangamRuthvik** [CCExtractor/taskwarrior-flutter#291]
### Describe your issue

When adding the task and selecting the date in input mode there are some pixel overflow errors

### Steps to reproduce

Go to Home Page
Start Adding new task
while setting the date choose the manual date input method
You can see the error

### What was the expected result?

Responsive UI

### Put here any screenshots or videos (optional)

![Screenshot (183)](https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/3eb702eb-35f0-43f8-adac-5200fc8d4968)

![Screenshot_20240210-235254 (1)](https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/bc6eefb3-0266-415f-a252-ff995e847434)

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by JangamRuthvik** [comment]
@Pavel401 Can you assign this to me

**Comment by JangamRuthvik** [comment]
@Pavel401 can you assign this to me

**Comment by JangamRuthvik** [comment]
@Pavel401 Should I focus solely on fixing the current part that is causing the error, or should I  consider locking the orientations of the app? by locking orientations we are telling that even if the device is tilted the app will be in portrait mode and functions as expected . Also  i don't find anywhere in the code we have used OrientationBuilder() widget or any other widget that handles the orientation part of the device and adjusts accordingly.

**Comment by Pavel401** [comment]
For now, lock the app to portrait orientation.

**Comment by Pavel401** [comment]
@JangamRuthvik this is already fixed right?

**Comment by JangamRuthvik** [comment]
yes, @Pavel401 the pr is merged and we can close this issue

**Comment by Pavel401** [comment]
> yes, @Pavel401 the pr is merged and we can close this issue
> 

Could you please mention the pr ?

**Comment by JangamRuthvik** [comment]
here is the pr
https://github.com/CCExtractor/taskwarrior-flutter/pull/293#issue-2128935983
