### ISSUE TITLE
Enhance Android Homescreen Widget to Display All Tasks

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/taskwarrior-flutter#292]
### Describe your issue

The current implementation of the homescreen widget on the Android side limits the visibility of tasks by displaying only the first three in the widget view. This can be inconvenient for users who have more than three tasks, as they may not see all their important items at a glance.

### Steps to reproduce

1. Go to widgets in android launcher 
2. Select Taskwarrior widget

### What was the expected result?

To enhance the user experience and provide better utility, we should modify the homescreen widget to display all tasks within the widget view. By doing so, users can easily access and manage all their tasks directly from the homescreen without the need to open the app.

**Update the widget layout to accommodate displaying multiple tasks.**

- Implement a scrolling mechanism or expandable/collapsible sections within the widget to accommodate varying numbers of tasks.
- Ensure that all tasks are fetched and displayed accurately, maintaining consistency with the app's task list.
- Test thoroughly across different device resolutions and orientations to ensure optimal display and functionality.

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by its-me-abhishek** [comment]
Can I work on this issue?

**Comment by JangamRuthvik** [comment]
@Pavel401  can i work on this issue?

**Comment by Pavel401** [comment]
@its-me-abhishek, you can look at this example: [https://github.com/nguyenletrongnhanofficial/todoai_fe](example). This developer has implemented a similar todo homescreen widget.

**Comment by JangamRuthvik** [comment]
@Pavel401 the link is not valid

**Comment by its-me-abhishek** [comment]
sure, and it's working by copy-pasting it directly @JangamRuthvik , instead of clicking on the hyperlink

**Comment by JangamRuthvik** [comment]
@Pavel401 i am almost done with the issue.please a look at screenshot and screenrecorded video . tasktitle and urgencylevel is not getting displayed.soon i will do that also.
![abc](https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/b890b8f9-f781-4a80-b408-e8750ef5401c)

https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/e9c85c3d-ab0a-46ee-9b75-b73e94df93bc

**Comment by JangamRuthvik** [comment]
Hey @Pavel401 i am just done with the issue . please have a look at it and provide a review

https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/354adda9-8cb0-4988-b08b-5adcebbd9280

**Comment by Pavel401** [comment]
> @Pavel401 i am almost done with the issue.please a look at screenshot and screenrecorded video . tasktitle and urgencylevel is not getting displayed.soon i will do that also. ![abc](https://private-user-images.githubusercontent.com/122552365/304487888-b890b8f9-f781-4a80-b408-e8750ef5401c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTY4OTgsIm5iZiI6MTcwNzg1NjU5OCwicGF0aCI6Ii8xMjI1NTIzNjUvMzA0NDg3ODg4LWI4OTBiOGY5LWY3ODEtNGE4MC1iNDA4LWU4NzUwZWY1NDAxYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QyMDM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzM5ZGMwMWRhMDEyNzIzMDliN2JmNDM4NzE2NjgyZjUxYjRhMjc4MzU5ZTY3MGJmYzcxYjcwYmQ2NDIzNjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.runImXQpqsOFx3CbFMgJyIPlmXx0AWgL8D5hTmWi1yQ)
> 
>  sample.mp4

Amazing 🚀

**Comment by JangamRuthvik** [comment]
Hey @Pavel401 i am done with the issue. Please have a look at it and provide feedback

Uploading completedWork.mp4…

**Comment by JangamRuthvik** [comment]
Hey @Pavel401 i am done with the issue. Please have a look at it and provide feedback

https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/58f46ead-f9bb-4b46-8ea5-8db33d9d20ca

**Comment by JangamRuthvik** [comment]
should i change any ui design like text color or just push the code @Pavel401

**Comment by Pavel401** [comment]
@JangamRuthvik yes, send the PR.

@its-me-abhishek if you are still working on this then send your PR too.

I'll consider whoever's solution works best for this.

**Comment by JangamRuthvik** [comment]
@Pavel401  i just now pushed the code

**Comment by its-me-abhishek** [comment]
I had actually working on another approach,  I went for making buttons to go through the tasks, as scrolling on widgets usually collides with the Android drawer gestures, and the first approach is quite similar to what @JangamRuthvik has implemented. Would push the second one as it's done, the first one needs a bit of workaround to make the buttons work perfectly.

**Comment by JangamRuthvik** [comment]
Well @its-me-abhishek that was a great idea . So instead of  writing code again to implement that scrolling mechanism you can take the work from where I left and add a button that you wish  in layout file and corresponding logic in kt file. what would you say @Pavel401 . Excuse me if I said anything wrong

**Comment by JangamRuthvik** [comment]
Hello sir,during my proposal for GSOC I wanted to mention my pr's .so if
the pr is closed I can't get link to mention this.

**Comment by JangamRuthvik** [comment]
Is there anyway to show that I have made this pr?

**Comment by Pavel401** [comment]
@JangamRuthvik check the closed [prs](https://github.com/CCExtractor/taskwarrior-flutter/pulls?q=is%3Apr+is%3Aclosed) , just copy the url from there .

**Comment by JangamRuthvik** [comment]
@Pavel401 sir,can you add any difficulty label  of the issues so that we can mention in our proposal's.

**Comment by JangamRuthvik** [comment]
Thank you @Pavel401 for adding the label as requested
