### ISSUE TITLE
Enhancement:  UI fixes in alert dialogs

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#298]
### Describe your issue

Currently, the alert dialogs throughout the app are not consistent with the app's themes and colors. 
To make them more visually appealing and cohesive, we can introduce a consistent style, similar to the one in `Add Task` dialog box. This way, users will have a more appealing experience across the app.

### Steps to reproduce

1. Save or edit projects, tasks, and tags to observe changes.
2. On the Profiles page by deleting, exporting, or renaming profiles.

### Put here any screenshots or videos (optional)

<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/1a106c89-f7ae-413d-956c-40fa2dd43fcc" alt="IMG-20240217-WA0002" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/de4144d2-2e2d-4bf5-a81a-91f4d8672bd5" alt="IMG-20240217-WA0003" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/2dc13d7c-f9eb-4530-bc0d-09ce4579849a" alt="IMG-20240217-WA0004" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/f2f1f2de-b6a4-4530-986d-700edabbf1a0" alt="IMG-20240217-WA0005" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/4dbfe54d-973c-4062-885d-47e650a94c75" alt="IMG-20240217-WA0006" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/aebe7f69-b579-4f95-a362-6d3370a68eeb" alt="IMG-20240217-WA0007" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/f3321526-9037-4c99-8c5d-0c2020dd9ae7" alt="IMG-20240217-WA0008" height="250px">
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/b11964f9-dcb5-4af2-98a7-e213df80d6cc" alt="IMG-20240217-WA0009" height="250px">

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by its-me-abhishek** [comment]
@Pavel401 can I work on this issue?

**Comment by JangamRuthvik** [comment]
I think we can use extension method on alert dialog widget and create all UI designs like,be it colour or be it border radius and other elements I think it will be the most optimised code
@Pavel401 what do you think?

**Comment by Pavel401** [comment]
>  I think we can use extension method on alert dialog widget and create all UI designs like,be it colour or be it border radius and other elements I think it will be the most optimised code
> @Pavel401 what do you think?

Discuss with @its-me-abhishek about the most effective implementation.

**Comment by JangamRuthvik** [comment]
@its-me-abhishek instead of creating those border radius in every dialog and other elements that are common,you can use extension method on alert dialog and easily use the same code again and again.what do you think and the most optimised one can be created a alert dialog util.dart and then pass the title text,call back functions and then import this in necessary files.Actually i wanted to work on this but helping other team mates can also be a great choice.what do you think @its-me-abhishek and @Pavel401
