### ISSUE TITLE
UI inconsistency for back button in the 

### ISSUE THREAD

**Issue by MarkisDev** [CCExtractor/taskwarrior-flutter#3]
The back button color is inconsistent (and is not very visible) on the task details page.
Look at the picture for reference.

![qemu-system-x86_64_gIJczevVl9](https://user-images.githubusercontent.com/28730791/192105742-84d7c94c-737b-4189-a162-e81a70f8f6b6.png)

If this is unintended, I'd like to work on it!

**Comment by NishantSinghal19** [comment]
Make the pull request and then i will review and merge it
