### ISSUE TITLE
Improve Font Management through an app-wide global class

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#301]
### Describe your improvement idea or feature request

The current implementation relies on hardcoded fonts, posing challenges in managing and updating the overall font theme of the app. This issue suggests the introduction of system-wide global classes for fonts, creating a class named `TaskWarriorFonts` in config folder. This enhancement will enhance the maintainability of the app and simplify the process of updating and customizing fonts throughout the application.

### How would you like to see it implemented?

Implement a configuration/class for fonts in the application, for convenient access to the diverse fonts and styles being used in the app.

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by JangamRuthvik** [comment]
@Pavel401 can you assign any issue to me?

**Comment by Pavel401** [comment]
> @Pavel401 can you assign any issue to me?

Someone is already working on this one

**Comment by JangamRuthvik** [comment]
> > @Pavel401 can you assign any issue to me?
> 
> Someone is already working on this one

If you have any issues in mind I think I can help in solving that

**Comment by Pavel401** [comment]
> > > @Pavel401 can you assign any issue to me?
> > 
> > Someone is already working on this one
> 
> If you have any issues in mind I think I can help in solving that

Recently someone made a pr and added desktop support.
So could you test the desktop version of this app and optimise the app for the desktop.

Test all things and make sure everything is working.

If you find any issues create a PR for that.
