### ISSUE TITLE
Urgency Level Indicator

### ISSUE THREAD

**Issue by JangamRuthvik** [CCExtractor/taskwarrior-flutter#304]
### Describe your improvement idea or feature request

Instead of showing values we can define an upper limit and lower limit of indicator and show the urgency Level

### How would you like to see it implemented?

1.Open the App

### Put here any screenshots or videos (optional)

https://github.com/CCExtractor/taskwarrior-flutter/assets/122552365/b8bad086-ca29-432e-a431-eaa4d774ff79

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by JangamRuthvik** [comment]
just gave it a try(above video) .want to know your opinion @Pavel401

**Comment by its-me-abhishek** [comment]
the red, yellow, green and grey colors are supposed to represent the urgency levels as well

**Comment by Pavel401** [comment]
> the red, yellow, green and grey colors are supposed to represent the urgency levels as well

<img width="322" alt="Screenshot 2024-02-21 at 10 06 03 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/80409db4-8774-46ac-9173-3f8981003dee">
