### ISSUE TITLE
Add the new taskwarrior readme in the app

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/taskwarrior-flutter#307]
### Describe your issue

 String url = "https://github.com/Pavel401/taskwarrior-flutter/blob/main/README.md#taskserver-setup";

replace this with the current readme of the task warrior repo under ccextractor.

### Steps to reproduce

1. Go to lib/taskserver/ntaskserver.dart
2. Line number 346

### What was the expected result?

Make sure when the website opens, it should automatically point to the setup guide.

### Put here any screenshots or videos (optional)

<img width="1470" alt="Screenshot 2024-02-22 at 1 33 11 AM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/f9268f1a-b090-47e0-ade2-e2292a03c13b">

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by JangamRuthvik** [comment]
@Pavel401 can you assign this to me

**Comment by JangamRuthvik** [comment]
@Pavel401 i have solved it can you check the pr

**Comment by JangamRuthvik** [comment]
@Pavel401 you added the difficulty label for this pr. Can you add the same difficulty level here also. The label you assigned was medium for this pr.
