### ISSUE TITLE
Display User-Friendly Error Message for Unconfigured Task Server on Statistics Page

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/taskwarrior-flutter#308]
### Describe your issue

Currently, when a user clicks on the Statistics button without having configured the Task Server, the application fails to display a relevant error message. This lack of clear feedback can lead to confusion for users, as they are not informed about the necessity of setting up the Task Server to access statistics functionality. To enhance user experience and provide clear guidance, a more descriptive and user-friendly error message should be implemented.

### Steps to reproduce

1. Go to lib/taskserver/ntaskserver.dart
2. line 72 (_showStatistics)

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Sabra-xD** [comment]
Hey, Pavel. Can you assign me this issue? @Pavel401
