### ISSUE TITLE
[IMPROVEMENT] Theme synchronization of different drawer and pages

### ISSUE THREAD

**Issue by 100RAV-AGGARWAL** [CCExtractor/taskwarrior-flutter#31]
Theme synchronization of Filter drawer, Profile Page, Task details

![TW 3](https://user-images.githubusercontent.com/81032655/194319216-0b8fa411-eeb3-4277-a2a7-04123baf8ef2.jpeg)
![TW 4](https://user-images.githubusercontent.com/81032655/194319466-a28cf957-ef45-4d4a-979e-02830d8cfaef.jpeg)

These have theme inconsistency with Dark theme..I would like to work on these UI improvements

**Comment by 100RAV-AGGARWAL** [comment]
Also there is some rendering issue in tags section of task details

**Comment by bhav-khurana** [comment]
> Also there is some rendering issue in tags section of task details

which issue are you talking about exactly?
