### ISSUE TITLE
Setting alert time clock in the past.

### ISSUE THREAD

**Issue by Sabra-xD** [CCExtractor/taskwarrior-flutter#312]
### Describe your issue

Right now when the user sets the time to be alerted for their task through the clock. You can set the time to be in the past, as in if it is currently 2PM. The alert time can be set to 1PM.

### Steps to reproduce

None

### What was the expected result?

To only be able to set the alert time in the future.

### Put here any screenshots or videos (optional)

https://github.com/CCExtractor/taskwarrior-flutter/assets/52329758/ac27af8a-94d9-4595-8f7e-6ea1ec842e3d

### How can we contact you (optional)

None

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by cfsmp3** [comment]
I'm not 100% sure this is a bug; obviously you won't be able to do something by the due date if it's in the past, but at the same time I might have forgotten to add a task in the past and I want to add it now while maintaining the original due date, so I know how late I am.

I think I'd leave it at is. Or maybe allow it but display a dialog about it in case the user is just making a mistake.

**Comment by Sabra-xD** [comment]
Alright. Anyway, the due time is set to Due: - in this case which needs to be adjusted. 
And I think the design for over due tasks should be unique to catch the user's attention and sets it out from the current scheduled tasks.

**Comment by Pavel401** [comment]
I think we should display a snack bar message if the user sets a past time instead of considering it as a bug, as mentioned by @cfsmp3.

**Comment by Sabra-xD** [comment]
I found a snackBar was already being used but it was not in-foucs since it used ScaffoldMessanger and we were working on the AlertDialog, so it displayed the snackBar message in the Scaffold.
So, I deleted it and added FlushBar to be able to display the message in the current context.

Also I high lighted the time, if it was now or in the past, set it to red just to get user's attention.
You can check out the PR.  https://github.com/CCExtractor/taskwarrior-flutter/pull/314

**Comment by Pavel401** [comment]
Fixed in https://github.com/CCExtractor/taskwarrior-flutter/pull/315
