### ISSUE TITLE
About Text out of bounds.

### ISSUE THREAD

**Issue by Sabra-xD** [CCExtractor/taskwarrior-flutter#316]
### Describe your issue

The Package mentioned in the Text is going out of bounds.

### Steps to reproduce

None

### What was the expected result?

Text remaining in Bounds.

### Put here any screenshots or videos (optional)

![Screenshot_2024-02-25-02-00-51-80_9bdaab249332ff0aa81548d24e981681](https://github.com/CCExtractor/taskwarrior-flutter/assets/52329758/e83ba8f3-d41a-49d6-9132-abce4d19e86e)

### How can we contact you (optional)

None

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
Fixed in https://github.com/CCExtractor/taskwarrior-flutter/pull/315
