### ISSUE TITLE
Better display for tasks.

### ISSUE THREAD

**Issue by Sabra-xD** [CCExtractor/taskwarrior-flutter#318]
### Describe your improvement idea or feature request

Better display for tasks.
Since familiar UI is the best UI.
Vast majority of Task scheduling applications offer an order of display.
1-Over due tasks
2- Today
3- Tomorrow
4- Scheduled for later
in that order.

I suggest this improvement since if you're not familiar with the application you won't be able to see which task is overdue, since nothing makes it unique from other tasks.

### How would you like to see it implemented?

None

### Put here any screenshots or videos (optional)

None

### How can we contact you (optional)

None

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
We have priority, urgency, and a set of other parameters to sort the tasks . If you open the right side filter drawer you can access those.

How can you improve the existing design? 
Please share some mockups or something.

**Comment by Sabra-xD** [comment]
![example](https://github.com/CCExtractor/taskwarrior-flutter/assets/52329758/dfc10c16-ad58-4204-ab5a-96eb360d10ef)

We'd display them according to their due date.
Since having all the tasks in one page only ordered in the time they were added can be a bit confusing for users.
Basically the feature is, closer due date is @ the top of the screen, the furthest goes to the bottom. And a few UI improvements like in the screenshot.
