### ISSUE TITLE
Adding wait time causes the notification to be issued twice @ the same time.

### ISSUE THREAD

**Issue by Sabra-xD** [CCExtractor/taskwarrior-flutter#319]
### Describe your issue

Once a task is created, accessing the task and adding a wait time, which I assume is the time the user requests to be notified of the task again, causes the task notification to be sent twice once the task is due.

I assume that the wait time must come before the second notification is sent out.

Also, the back ground color is not compatible with the chosen theme light/dark mode. It's just set to light mode.

### Steps to reproduce

None

### What was the expected result?

None

### Put here any screenshots or videos (optional)

![2 notifications](https://github.com/CCExtractor/taskwarrior-flutter/assets/52329758/bf37648f-895b-46b8-adfa-91900d6e8c5c)
![Screenshot_2024-02-27-07-25-14-37_9bdaab249332ff0aa81548d24e981681](https://github.com/CCExtractor/taskwarrior-flutter/assets/52329758/cf7a1ad5-63e1-41a6-9392-8efb1570e489)

### How can we contact you (optional)

None

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Pavel401** [comment]
<img width="1470" alt="Screenshot 2024-02-28 at 8 15 49 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/47685150/d5023662-47a4-449b-a868-965f0473b97b">

I have set the wait and due time on the same date, only the time is different. However, I have received only one notification according to the due date. For the wait time, I did not receive any notifications.

**Comment by Sabra-xD** [comment]
I sat the wait time to be after the due time and it gave me 2 notifications once the due time was on.

Video:

https://drive.google.com/file/d/1-O1gCb3nDbAtEz_JbdO7Hjltw34sZmDE/view?usp=sharing

**Comment by Pavel401** [comment]
Hi there! I just wanted to share my thoughts on receiving notifications for tasks with due dates. In my opinion, it's perfectly fine to receive two notifications - one on the due date and another a bit earlier to remind us that the deadline is approaching. 

I also found some information on the official documentation which states that we can use a "wait" date to hide tasks that are far into the future and we don't want to see them on our lists until it gets closer to the due date. For example, we can use the command "task 1 modify wait:30th" to hide a task until the 30th of the month. This way we won't be distracted by tasks that are not relevant yet. 

It's important to note that a due date is not required to use the "wait" feature. I hope this helps clarify things!
