### ISSUE TITLE
[BUG] There is invalid date format when changing in task details page

### ISSUE THREAD

**Issue by NishantSinghal19** [CCExtractor/taskwarrior-flutter#33]
There is date format error in taskdetails page when changing due or date related things

**Comment by bhav-khurana** [comment]
Which error are you talking about exactly?

**Comment by NishantSinghal19** [comment]
Check details of task and change due and during debugging this issue is coming

**Comment by 100RAV-AGGARWAL** [comment]
#36 

Bug fixed...kindly review it
