### ISSUE TITLE
Adding Option of Listview/Gridview 

### ISSUE THREAD

**Issue by codesage01** [CCExtractor/taskwarrior-flutter#333]
### Describe your improvement idea or feature request

🚀 New Feature Highlight: Enhanced User Interaction in GridView and ListView,

1.Dynamic Customization: Users now have the freedom to personalize their experience by adding their preferred options directly within the GridView or ListView. Whether it's organizing items, prioritizing tasks, or customizing views, this feature empowers users to tailor the app to their unique needs.

2.Streamlined Workflow: Gone are the days of navigating to separate settings or menus to add new options. With this feature, users can seamlessly add items on-the-fly, right within the context of the GridView or ListView. This streamlines the workflow, saving time and enhancing usability.

3.Visual Clarity: By integrating the add option directly within the GridView or ListView, we maintain visual consistency and clarity. Users can easily identify where to add new items without any confusion, resulting in a more intuitive and user-friendly experience.

4.Improved Engagement: Offering users the ability to add options directly within GridView and ListView enhances engagement and interactivity. It encourages users to actively participate in shaping their experience, fostering a deeper connection with the app.

5.Developer Friendly: From a development perspective, implementing this feature is straightforward and seamlessly integrates with existing GridView and ListView functionalities. It's a win-win for both developers and users.

### How would you like to see it implemented?

1.Go to setting
2.Enable GridView

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Gaurav-Kushwaha-1225** [comment]
Can you assign this issue to me..

**Comment by Pavel401** [comment]
> Can you assign this issue to me..

This is not needed.
