### ISSUE TITLE
Choose a tag to (optionally) assign to a newly created task

### ISSUE THREAD

**Issue by mrshu** [CCExtractor/taskwarrior-flutter#338]
### Describe your improvement idea or feature request

In order to follow the GTD methodology a bit better, it would be great to be able to set a tag (say `in`) to assign to the newly created tasks, so that they are automatically on the `in` list.

### How would you like to see it implemented?

1. Click on + to add a new task
2. Fill the task in
3. Have the option to choose a tag for the task (literally just via an input box), with a default being set to something defined in the settings
4. After submission, the task is created with a specific tag

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by BrawlerXull** [comment]
@Pavel401 the feature is already implemented I suppose
is there any other feature required?
![Uploading Screenshot 2024-05-07 at 10.08.10 AM.png…]()

**Comment by mrshu** [comment]
It's awesome to see this this exists!

How can one install the version that would have this feature implemented? The one at https://play.google.com/store/apps/details?id=com.ccextractor.taskwarriorflutter seems to be from 2023 still...

Thanks!
