### ISSUE TITLE
`modifyTaskOnTaskwarrior` fails silently

### ISSUE THREAD

**Issue by sternj** [CCExtractor/taskwarrior-flutter#369]
### Describe your issue

`modifyTaskOnTaskwarrior` fails silently when `ccsync` is enabled and returns a 500 error code. The result of the `http.post` call is not used.

### Steps to reproduce

This follows from the code in `api_service.dart`

### What was the expected result?

An error should somehow be surfaced, perhaps through a toast.

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by rohansen856** [comment]
the `modifyTaskOnTaskwarrior` function inside `api_service.dart` does not use a try catch structure and the `http.post` call's result is not captured and used. We should update the code there:
```dart
  await http.post(
    Uri.parse(apiUrl),
    headers: {
      'Content-Type': 'text/plain',
    },
```
We can use the ScaffoldMessanger component to properly show the message like this:
```dart
if (response.statusCode != 200) {
    ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Error: ${response.statusCode} - ${response.reasonPhrase}"))
    );
}
```
to possibly capture the returning response and based on it's status code give appropriate toast message based on that.
As mentioned in the above comment, not just HTTP 500 error but also success message should also be shown to the user. 
If it's open to contribution, i would like to work on it. Thank you.
