### ISSUE TITLE
Add task -- Better UX

### ISSUE THREAD

**Issue by aakashgarg-19** [CCExtractor/taskwarrior-flutter#38]
![image](https://user-images.githubusercontent.com/71538277/194672788-0f961d52-dce1-44df-820c-2e8b66c235c1.png)

Here instead of null in due, an icon of clock would be a nice add on to UX

**Comment by aakashgarg-19** [comment]
I would like to work on this issue, @NishantSinghal19 please assign me  this issue

**Comment by NishantSinghal19** [comment]
Can you please show the design here that how it will look ? Then I will check then assign the issue
