### ISSUE TITLE
Branding tweaks: Taskwarrior or taskwarrior not TaskWarrior or Task Warrior

### ISSUE THREAD

**Issue by linuxcaffe** [CCExtractor/taskwarrior-flutter#386]
### Describe your issue

Not a huge bug, but a branding standardization. I see variations of the name Taskwarrior across this app, and I humbly suggest that we keep it consistent with the rest of the task ecosystem. 

Also, because this is an app that represents a badass CLI app, where commands are case sensitive, showing or referring to such commands in the UI should use lower case.

### Steps to reproduce

See the widget (Task Warrior) and .. somewhere else, TaskWarrior, change them ;-)

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by rohansen856** [comment]
I would like to contribute to this issue. I believe this is quite a small issue and can be solved very fast. If its up for grab please assign me @Pavel401 .

**Comment by linuxcaffe** [comment]
Yay! neatly done!

**Comment by Pavel401** [comment]
Thanks @rohansen856
