### ISSUE TITLE
bug: Add task dialog

### ISSUE THREAD

**Issue by rohansen856** [CCExtractor/taskwarrior-flutter#390]
### Describe your issue

In the add task dialogue I found 3 main issues:
- the due task field shows `Add task` while it should be a button and should say something like `Pick Date`.
- the add task model's width is too much in larger screens. It should have a width limit.
- the date field in dark mode isn't even visible. We should change its color.

### Steps to reproduce

1. Run the app using `flutter run`
2. Tap on the add button on the bottom right corner

### Put here any screenshots or videos (optional)

![Screenshot from 2024-11-27 20-47-31](https://github.com/user-attachments/assets/fd20bde9-3886-4893-ab92-b61a35de29cc)

![Screenshot from 2024-11-27 20-53-15](https://github.com/user-attachments/assets/16f116aa-990e-4c86-a4ce-b72e71fe35f7)

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by linuxcaffe** [comment]
related to #384

**Comment by rohansen856** [comment]
> related to #384

Oh... sorry for the confusion. closing this.
