### ISSUE TITLE
The app always starts in dark mode whenever I open it

### ISSUE THREAD

**Issue by The-CoderBoy** [CCExtractor/taskwarrior-flutter#393]
### Describe your issue

 if I switch to light mode and leave the app, it reverts to dark mode when I reopen it.

### Steps to reproduce

1. open app
2. tab on hemberger icon
3. tab on moon icon, right side of Menu text ( now it switch to light theme )
4. leave the app
5. open app ( now its again in dark mode )

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by BrawlerXull** [comment]
Please add a video replicating the unexpected behaviour as it is working fine on my local machine.

**Comment by The-CoderBoy** [comment]
https://github.com/user-attachments/assets/f5be98e4-ad49-450c-9686-baaa20014623

Here it is

**Comment by The-CoderBoy** [comment]
i am using version 2.0.0
