### ISSUE TITLE
feat: Homepage Drawer menu UI improvement

### ISSUE THREAD

**Issue by rohansen856** [CCExtractor/taskwarrior-flutter#397]
### Describe your improvement idea or feature request

the current `homepage drawer menu` design (i.e. the `left sidebar`) has a really bland design. As a part of UI improvement I would like to redesign the right sidebar and add a few `animations` and also `colors`. The design would preserve all the previous functionalities and improve the overall user experience.

### How would you like to see it implemented?

Currently I have a demo design ready for this purpose. I would like to go ahead with the redesign if approved.

total changes suggestion summary:
- Sidebar Header design change
- Tiles overall design change
- Tiles hover animation addition
- Hover Cursor Change for supported devices
- Exit dialog redesign and subtle entry animation

I would like to work on the issue and improve the design. Thank you.

### Put here any screenshots or videos (optional)

Demo design images:
![Screenshot from 2024-12-14 22-01-17](https://github.com/user-attachments/assets/131682aa-e30a-4f23-a4fa-69b129e99481)
![Screenshot from 2024-12-14 22-01-26](https://github.com/user-attachments/assets/afada159-ef37-4b63-9792-ec83cf5a7316)
![Screenshot from 2024-12-14 22-02-45](https://github.com/user-attachments/assets/48827109-3c88-4dbb-9a51-dbea8fed95c6)
![Screenshot from 2024-12-14 22-01-36](https://github.com/user-attachments/assets/1fb73f7a-89d8-410e-b96e-67ab423f6f51)

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by Vardhan-ysh** [comment]
I would like to work on this. Can I be assigned to the issue.

**Comment by rohansen856** [comment]
> I would like to work on this. Can I be assigned to the issue.

I have already done the work on ui... just waiting for maintainer's approval and review😅

**Comment by Pavel401** [comment]
Hey, I believe the current UI effectively fulfills the purpose of the Drawer. Technically, altering the UI won't result in significant changes. If you see any areas for improvement, please follow the Material 3 guidelines while retaining the original dark and light color themes; there's no need to use fancy colors or aesthetics.

**Comment by BrawlerXull** [comment]
Closing this issue for now.
Please feel free to reopen if you come up with some better designs as suggested by @Pavel401
