### ISSUE TITLE
feat: Improving ux for adding tags while adding task

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [CCExtractor/taskwarrior-flutter#398]
### Describe your improvement idea or feature request

After adding tags which has whitespace in between are not valid as per guidelines so after clicking on add task it shows an error snackbar.
It should be changed so that user will not have to delete tags and add differently without space.

### How would you like to see it implemented?

I propose to change this to 
1. while `addTag` we should split the input by whitespaces and add tags differently
2. while input change in `TextFormField` it should check if it ends with `whitespace`, if it, it should add the tag immediately but not if it has white space in between (not in end or start).

### Put here any screenshots or videos (optional)

![Error show after adding of tags](https://github.com/user-attachments/assets/32df8205-7c11-472e-a45d-dd9033c255f4)

### How can we contact you (optional)

Gh: @SGI-CAPP-AT2
Slack: shubham ingale

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by SGI-CAPP-AT2** [comment]
@BrawlerXull I will like to work on this. Please assign to me after review

**Comment by BrawlerXull** [comment]
Yes you can start working on it. But make sure it matches the theme and should work fine in both dark/light mode
