### ISSUE TITLE
Update modifyTaskOnTaskwarrior function to pass ID instead of UUID

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#408]
### Describe your issue

- Related to the [issue](https://github.com/CCExtractor/ccsync/issues/51).
- We should be passing taskID in the request instead of UUID in the request body in the modifyTaskOnTaskwarrior function in the API service

### Steps to reproduce

1. Go to a task
2. Edit a task
3. It would fail after some time

### What was the expected result?

The task should get edited

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by linuxcaffe** [comment]
@its-me-abhishek are you sure task ID is the better reference? Taskwarrior will change task IDs sometimes, like after "garbage collection", but the UUID doesn't change, so I would think, behind the scenes, UUID is the way to go.?

**Comment by its-me-abhishek** [comment]
task ID is the way to go I suppose in TW in order to modify a task, thus I have used it to build a command like: "task __id__ modify __description__", and so on then run it on the ccsync backend. so we need to send the task id (instead of the UUID that was being sent previously, and remained untested due to SQLite probably.)

**Comment by linuxcaffe** [comment]
Yes, task ID and UUID will both behave the same way in a command. The big difference is that a tasks ID can and will change. UUID is permanent unique identifier of a task. 

ID is easier for humans. 
UUID is better for code

**Comment by its-me-abhishek** [comment]
this makes sense, i think the problem might have been something else, and seems to be fixed after tweaking the backend a bit, as I have tested the app with the api. i will closing the issue. thanks for the help @linuxcaffe !
