### ISSUE TITLE
UI: a Way Better Widget - mockup

### ISSUE THREAD

**Issue by linuxcaffe** [CCExtractor/taskwarrior-flutter#415]
### Describe your improvement idea or feature request

It's great that there's a widget.. sadly.. it's a terrible widget! 

A good widget should;
- be able to share the screen with other icons (this one's huge!)
- follow the app color theme (this one come in light theme only)
- follow the app filter and sort (this one ignores filters and sorts on ID only)
- show as many tasks as practical
- feature an Add Task button

Here's a mockup of what I think would be a much better widget!

### How would you like to see it implemented?

widget gets a workover.. unfortunately, I don't know how to do that :-)

### Put here any screenshots or videos (optional)

![better_widget](https://github.com/user-attachments/assets/d3b1aa5c-d2a7-49ff-b3ed-0c2ca5edd3b8)

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by SGI-CAPP-AT2** [comment]
Hey @Pavel401 I can work on this issue. 

cc: @linuxcaffe

**Comment by SGI-CAPP-AT2** [comment]
Thanks assigning @Pavel401 
The PR #402 will be independent from this update
Since we've to update widget explicitly when theme toggle happens
ThemeData won't help there we've to use native approach or hardcoded colors.
