### ISSUE TITLE
Landing Page and Text Controller in search bar

### ISSUE THREAD

**Issue by dubey2709** [CCExtractor/taskwarrior-flutter#42]
We can add some animated texts on the landing page of App and also we can add a text controller in search bar in order to clear everything in search bar when hit enter.

**Comment by NishantSinghal19** [comment]
Like what?

**Comment by dubey2709** [comment]
Auto clear search bar after every search to enhance user experience

**Comment by dubey2709** [comment]
And typewriter animation on lading page

**Comment by NishantSinghal19** [comment]
Show some sample or make pr
