### ISSUE TITLE
improve the theme changing animation.

### ISSUE THREAD

**Issue by sainideepanshu199** [CCExtractor/taskwarrior-flutter#57]
the side drawer closes automatically after changing theme , also the animation is not smooth.

https://user-images.githubusercontent.com/114583893/207407621-909b116e-9079-4b65-ae64-56a698c6f86e.mp4

**Comment by NishantSinghal19** [comment]
What solution will you offer?

**Comment by amitamrutiya2210** [comment]
![207030932-ca6ce74e-eb45-4559-938a-affc4e83d841](https://user-images.githubusercontent.com/91112485/210163039-52cea371-955d-4688-86e2-ed8329444bfa.gif)

I think Circular change animation in app drawer like this look's great. What you say @NishantSinghal19 ?

**Comment by Rushour0** [comment]
> ![207030932-ca6ce74e-eb45-4559-938a-affc4e83d841](https://user-images.githubusercontent.com/91112485/210163039-52cea371-955d-4688-86e2-ed8329444bfa.gif) [ ![207030932-ca6ce74e-eb45-4559-938a-affc4e83d841](https://user-images.githubusercontent.com/91112485/210163039-52cea371-955d-4688-86e2-ed8329444bfa.gif) ](https://user-images.githubusercontent.com/91112485/210163039-52cea371-955d-4688-86e2-ed8329444bfa.gif) [ ](https://user-images.githubusercontent.com/91112485/210163039-52cea371-955d-4688-86e2-ed8329444bfa.gif)
> 
> I think Circular change animation in app drawer like this look's great. What you say @NishantSinghal19 ?

The colour changing is not viable as suggested in this above example, because the theme is not actually being set globally. All the colours are being changed manually through boolean and there is no use provider in the app

**Comment by amitamrutiya2210** [comment]
Yes for Circular change animation in app have to set theme globally and rewrite a code.

**Comment by NishantSinghal19** [comment]
I am interested in this circular change animation and as theme is not globally , first set theme globally and side by side implement this , so any of two can submit me  a pr , I will review that

**Comment by amitamrutiya2210** [comment]
Okay I will implement circular change animation and submit a PR .

**Comment by Rushour0** [comment]
> I am interested in this circular change animation and as theme is not globally , first set theme globally and side by side implement this , so any of two can submit me  a pr , I will review that

Alright works

**Comment by Pavel401** [comment]
@amitamrutiya2210 any update? or else I will work on this.

**Comment by amitamrutiya2210** [comment]
@Pavel401 work is on progress.

**Comment by amitamrutiya2210** [comment]
Hey @Pavel401, if you want to work, please go ahead.

**Comment by Pavel401** [comment]
@amitamrutiya2210 , Okay I will work on this.

**Comment by shivanshu814** [comment]
I want to contribute to this repository

**Comment by manoj1749** [comment]
Are you working on this issue still @Pavel401 ?

**Comment by Pavel401** [comment]
> Are you working on this issue still @Pavel401 ?
> 

Yes , I am still working on this issue.

**Comment by manoj1749** [comment]
I feel this was a small issue to work on and this issue is being inactive since a week, that's why I had asked

**Comment by manoj1749** [comment]
I feel this was a small issue to work on and this issue is being inactive since a week, that's why I had asked

**Comment by Pavel401** [comment]
> I feel this was a small issue to work on and this issue is being inactive since a week, that's why I had asked

Sorry, I am busy with my exams. You can work on this.

**Comment by manoj1749** [comment]
Yeah sure, thanks!!

**Comment by lilmistake** [comment]
Any updates on this?

**Comment by andoriyaprashant** [comment]
Hey @NishantSinghal19 I would like to work on this task. Could you please assign it to me
Thank you

**Comment by andoriyaprashant** [comment]
Hey @NishantSinghal19  @Pavel401  I would like to work on this task. Could you please assign it to me
Thank you

**Comment by Pavel401** [comment]
@andoriyaprashant
Assigned it to you.
I am working on other parts of the app.

**Comment by andoriyaprashant** [comment]
Thank you for assigning the task 👍
