### ISSUE TITLE
Wiki is inconsistent 

### ISSUE THREAD

**Issue by MarkisDev** [CCExtractor/taskwarrior-flutter#6]
Hey, just wanted to point out that the Wiki seems to be inconsistent, especially in the Contribution guidelines and Development Practices section.

Might wanna change the channel name under Contribution Guidelines and the theme file (which doesn't exist in this repo afaik)

**Comment by NishantSinghal19** [comment]
Wiki doesn't contain in repo these are separate GitHub pages

**Comment by MarkisDev** [comment]
Yup, I was just letting you know in order to avoid confusion :) 
Thank you!
