### ISSUE TITLE
[Enhancement ] Adding local notification to remind user about their task deadline.

### ISSUE THREAD

**Issue by Interstellar07** [CCExtractor/taskwarrior-flutter#63]
Hi @NishantSinghal19 

The app is fantastic, but I'd like to work on an improvement that will allow users to be reminded about their tasks beforehand via  local notification on their phones in case they forget to complete them by the deadline or if they do not mark them as completed. It will help them manage their tasks in a more efficient way.

**Comment by NishantSinghal19** [comment]
I am assigning this issue , you can use local notification package for this

**Comment by Interstellar07** [comment]
> I am assigning this issue, you can use local notification package for this

Okay, thanks

**Comment by kunal-iitj** [comment]
@Interstellar07 are you still working on this.

**Comment by Interstellar07** [comment]
> @Interstellar07 are you still working on this.

Yess, I am on it

**Comment by NishantSinghal19** [comment]
Now Android Work is done, if some want to work for local notifications in iOS tag me in this issue, and I will assign it

**Comment by kartikkhatana** [comment]
Hi @NishantSinghal19 
Please assign me the task for local notifications in iOS. I have already performed the necessary changes for iOS and the notifications are working perfectly on iOS.

**Comment by kartikkhatana** [comment]
Hey @NishantSinghal19 any update regarding the assigning of the task?
