### ISSUE TITLE
[IMPROVEMENT] UI Changes on the Task Card 

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/taskwarrior-flutter#65]
**fix: A bug fix in the project**
refactor: Regular code refactoring and maintenance

The Task cards on the home screen have no border-radius property on the InkWell.The splash radius should be similar to the radius of the card.

Before        |  After
:-------------------------:|:-------------------------:
![Screenshot_1673334390](https://user-images.githubusercontent.com/47685150/211485643-8e78a950-d3c4-430c-b531-49ad6305142b.png)|![Screenshot_1673334742](https://user-images.githubusercontent.com/47685150/211485715-bb9eec97-6374-4c64-9440-fd9a545418f9.png)

Please assign me to work on this issue @NishantSinghal19 .

**Comment by sainideepanshu199** [comment]
is this issue still open , can i work on it. please assign if issue is still unsolved.
