### ISSUE TITLE
Adding the Done Button at Each Card

### ISSUE THREAD

**Issue by ALIRAZA17** [CCExtractor/taskwarrior-flutter#71]
feat: Hi @NishantSinghal19 
This app is quite beautiful but there is a problem with it that I think we should add. There is no done button on the card so say if user has done his work before the due time he cannot delete that work because there is no button to do it. If you want this feature I can add it easily on the cards and provide the relevant functionality. Hoping to hear from you soon on this issue....

**Comment by NishantSinghal19** [comment]
You can give me pr , i can check it out if it works perfectly I will merge it

**Comment by ALIRAZA17** [comment]
> You can give me pr , i can check it out if it works perfectly I will merge it
> 
> 

On it
