### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by savitore** [CCExtractor/taskwarrior-flutter#77]
feat:
I want to add a "Pull to Refresh" option on the Home Screen.

style:
We can remove the Refresh option in the Nav drawer and add "Pull to Refresh" on the Home Screen to make it convenient for the users.

Please assign this to me.

**Comment by gvjkumar2004** [comment]
I am familiar with this,  Please assign this issue to me!

**Comment by savitore** [comment]
@NishantSinghal19 please assign this to me.

**Comment by Pavel401** [comment]
Do we need to implement Pull to Refresh?
As soon as we change something in the Task details it automatically updates the task card on the homepage.

**Comment by savitore** [comment]
Yes, I agree but then we should remove the Refresh option from the Nav drawer.

**Comment by lalmani-15876** [comment]
please assign this to me.

**Comment by lalmani-15876** [comment]
please assign this to me.

**Comment by NishantSinghal19** [comment]
I made pull to refresh before that doesn't look good and also my mentor rejected that idea
