### ISSUE TITLE
[Enhancement] Double Press to Exit App

### ISSUE THREAD

**Issue by Interstellar07** [CCExtractor/taskwarrior-flutter#79]
Enhancement Statment: Taskwarrior needs to add a 'Double press back button to exit app' functionality which will prevent users from accidentally exiting the app by single pressing the back button.

On single press, app will prompt [via Toast message or Snackbar] users to press twice the back button to exit from the app.

I would like to contribute to this issue.
@NishantSinghal19 Please, assign me this.

**Comment by shivanshu814** [comment]
I want to contribute to this repository
