### ISSUE TITLE
Made some UI Changes on the Task Details Page

### ISSUE THREAD

**Issue by iam-sarthak** [CCExtractor/taskwarrior-flutter#80]
<html>
<body>

Before | After
-- | --
 ![before](https://user-images.githubusercontent.com/80532254/214592333-17c6369d-02d0-406e-bf5a-a8ed9fadcc5b.jpeg) | ![after](https://user-images.githubusercontent.com/80532254/214592667-48576950-3f13-4780-9fa3-2e0ce8f40a92.jpeg)

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Benefits of these changes:</p><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Seg
oe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text
-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Help user to understand that a particular place is Editable</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Give a much better UI Experience to End Users.</li></ul>
</body>
</html>

style: Feature and updates related to UI improvements and styling

**Comment by shivanshu814** [comment]
I want to contribute to this repository and want to get involved in GSoC discussions.

**Comment by Pavel401** [comment]
> I want to contribute to this repository and want to get involved in GSoC discussions.

Stop spamming everywhere.
To contribute to this project : 
- Run the project locally
- Find issues
- Open a new issue and ask for others' opinions.
- Fix the issue and send a pull request.

**Comment by NishantSinghal19** [comment]
Thanks @Pavel401 ko explaining him
