### ISSUE TITLE
[Enhancement] [Style] Green background colour of ChoiceChip if selected

### ISSUE THREAD

**Issue by achintya-7** [CCExtractor/taskwarrior-flutter#82]
![image](https://user-images.githubusercontent.com/67036708/215709014-535cac79-be31-4b08-9ff4-dcc189f1bfd1.png)
## A better visual approach could be to also colour the selected chip for better understanding and identification. Something like this
![image](https://user-images.githubusercontent.com/67036708/215709687-ac34ca9f-3ba1-4bb3-87d5-12701b199294.png)

**Comment by NishantSinghal19** [comment]
I think this is not necessary
