### ISSUE TITLE
[Bug] Complete or Delete Task prompt giving null exception if no due date was provided

### ISSUE THREAD

**Issue by achintya-7** [CCExtractor/taskwarrior-flutter#89]
## Issue
If we create a task without selecting the due date *{Im not entirely sure if it's a requirement or not}* and then later try to complete or delete it, it throws a null value exception as the due date is defaulted as null if nothing is provided. This subsequently causes an issue with the `FlutterLocalNotificationsPlugin` object as we have to pass an int value to the `notification.cancel()`  method which here is taken as the int value of dtb (DateTime?) object. It being nullable can cause issues with the app.

## How to replicate it
Make a task without setting a due date and then try to complete or cancel it.

## Gif/Video
![NullCheck](https://user-images.githubusercontent.com/67036708/217059141-c6f3b0d7-c4a9-4f07-ac08-595d86ba02ab.gif)

## Possible fix
A simple null check can solve this problem. We can check if dtb is a null value {like most of GO codebase} if it's a null value and then return the function with 0 as the value of `notification.cancel()` and pop the dialog box.

**Comment by manoj1749** [comment]
- heyy @achintya-7 , this bug was already reported in issue #87 
- And a pr #88  is also made regarding this
- check the other issues and pr's before making one

**Comment by achintya-7** [comment]
Oh my bad. How have you solved it though.

**Comment by manoj1749** [comment]
> Oh my bad. How have you solved it though.

Yeah I solved it made a pr also, I had made that pr regarding this bug along with another feature

**Comment by achintya-7** [comment]
Well, I gave it a read and didn't see any checks for null values. Also, I don't think combining 2 issues into a single PR is easy to go through and comprehend. I'll close this if the maintainer asks me to.

**Comment by manoj1749** [comment]
Yeah I had added one, where it makes due-date a mandatory field to enter for saving the tasks.
Ok then, let the maintainer decide.
