### ISSUE TITLE
Enhancing UI of Add profile button

### ISSUE THREAD

**Issue by bhav-khurana** [CCExtractor/taskwarrior-flutter#94]
On the profile page, we can add a floating action button instead of the normal button to add new profile. It will enhance the consistency in the UI of the app.
Please assign me this issue @NishantSinghal19

**Comment by Gitesg** [comment]
is this issue still open? or assigned to someone if no then assign to me

**Comment by abhinav52000** [comment]
I want to work on this issue Kindly assign it to me.
